= Developing
:link-repository: https://github.com/d4l-data4life/hc-fhir-sdk-kmp
:doctype: article
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

Guide for our development process, project setup and how to write code.

[discrete]
==== Table Of Contents

toc::[]

== Prerequisites

* link:https://developer.android.com/studio#downloads[Android Studio 7.0.2]
* link:https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot[Java 8] | link:https://developer.android.com/studio/write/java8-support[Limitations of Java language features and APIs] | https://jakewharton.com/d8-library-desugaring/[Desugaring]
* link:https://kotlinlang.org/[Kotlin 1.5.21]
* link:https://www.python.org/downloads/[Python 3.7.8]

== Installation

=== Install Java & Kotlin

You could use link:https://brew.sh/[Homebrew] to install on mac

[source,bash]
----
brew tap adoptopenjdk/openjdk
brew install adoptopenjdk11
brew install kotlin
----

OR The easiest way to install Java and Kotlin is to use link:https://sdkman.io/[SDK MAN]

Just open your terminal and enter:

[source,bash]
----
curl -s "https://get.sdkman.io" | bash
----

Follow the setup instructions and verify that your installation works:

[source,bash]
----
sdk version
----

If it shows you something like `5.11.5+713` then your good to continue.

Just install the mentioned dependencies:

[source,bash]
----
sdk install java 11.0.11.hs-adpt
sdk install kotlin 1.5.21
----

Check your installation by:

[source,bash]
----
java -version
kotlin -version
----

=== Install Python

It is recommended to use link:https://github.com/pyenv/pyenv[PyEnv] for managing dedicated python versions.

Use link:https://brew.sh/[Homebrew] to install it on mac:

[source,bash]
----
brew install pyenv
----

Make sure you are in the project root and install the correct Python version which is derived from `.python-version` file:

[source,bash]
----
pyenv install
----

=== Android Studio

For better interop with iOS you may install the link:https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile[Kotlin Multiplaform Mobile (KMM) plugin for Android Studio]. It let's you run, test and debug shared code on Android and iOS without switching the IDEs.

=== First time

As the project includes a Git submodule, this must be initialised on first use

[source,bash]
----
git submodule update --init --recursive
----

== Development Process

=== Features

Every change has to branch of from `main` and use this branch naming convention:

* `feature/{type_of_change}-{short_description}` or with ticket id `feature/{ticket_id}/{type_of_change}-{short_description}`

`main` must be always in releasable state.

==== Type Of Change

- *add* for new features or functionality
- *change* for changes in existing features or functionality
- *remove* for removed features or functionality
- *fix* for any bug fixes
- *bump* for dependency updates
- *security* in case of vulnerabilities

Examples:

- `feature/SDK-456/add-awesome-hashing-algorithm`
- `feature/add-awesome-hashing-algorithm`
- `feature/remove-not-so-awesome-algorithm`
- `feature/fix-algorithm-corner-case`
- `feature/bump-lib-to-1.3.0`

== Release

A release branches of from `main` branch with following pattern:

* `release/{major}.{minor}(.{patch})/prepare-{major}.{minor}.{patch}` while patch is optional

Add following changes:

* Update CHANGELOG.adoc by creating a new Unreleased section and change current unreleased to release version
* Update README.adoc `project-version` to release version
* Update the latest release badge link:assets/images/badges.adoc[HowTo]

Releases are automatically created when a tag in the form of `v{major}.{minor}.{patch}` is added.

== Develop

The source is divided into supporting code for JSON parsing and establishing the FHIR primitive type system (String, Dates, Integer, etc.) for link:http://hl7.org/fhir/STU3/datatypes.html[FHIR 3] and link:http://hl7.org/fhir/R4/datatypes.html[FHIR 4]

A big portion of the FHIR implementation is generated code, that could be found under `fhir/src-gen/commonMain/kotlin`. The generation is using link:https://github.com/gesundheitscloud/fhir-parser/[FHIR-Parser] and is controlled by `generateFhir.main.kts` script.

To trigger code generation just call `./generateFhir.main.kts` for all FHIR versions or add `fhir3`/`fhir4` to only generate one version.

=== Change FHIR

If you need to adjust one of the FHIR versions, it is located under `fhir/src/commonMain/kotlin` and the corresponding package `care.data4life.hl7.fhir.{fhir_version}`:

* `.json`: JsonParser
* `.model`: FHIR base type for that FHIR version
* `.primitive`: Implementation of FHIR primitives
Releases are automatically created when a tag in the form of `v{major}.{minor}.{patch}` is added.

=== Change FHIR code generation

If you need to adjust the generated code, have a look at `fhir/parser/{FHIR version}/templates`:

* `template-codesystems.kt`: the enums used to represent most FHIR type systems
* `template-dependencies`: not used at the moment
* `template-elementfactory.kt`: FhirHelper to define serialization and help with type mapping
* `template-resource`: FHIR model definition
* `template-unittest`: Test to validate the FHIR implementation

Additionally you could tweak the type mapping by altering `fhir/parser/{FHIR version}/config/mappings.py`.

=== How to add a new FHIR version

Add:

* New FHIR spec under `fhir-spec/hl7.org/fhir/{new FHIR version}/`
* New `config` and `templates` under `fhir/parser/{new FHIR version}/`
** Adjust them to your needs
* Base implementation
** FHIR model base `Fhir{new FHIR version}`
** FHIR primitives
** `Fhir{new FHIR version}Parser` and register it in `FhirParserFactory` alongside with it's JSON implementation
* new FHIR version handling to `generateFhir.main.kts`
* generated models, tests and validation resources by triggering generation

Validate your changes and resolve issues introduced by the new FHIR version.
