= Data4Life FHIR SDK
:link-repository: https://github.com/d4l-data4life/hc-fhir-sdk-kmp
:project-version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT LOGO -->
        <a href="https://github.com/d4l-data4life/hc-fhir-sdk-kmp">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>Data4Life FHIR SDK</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        HL7 FHIR Models as Kotlin Multiplatform library
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/hc-fhir-sdk-kmp/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/hc-fhir-sdk-kmp/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/hc-fhir-sdk-kmp/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/d4l-data4life/hc-fhir-sdk-kmp/actions">
            <img src="https://github.com/d4l-data4life/hc-fhir-sdk-kmp/actions/workflows/d4l-ci-latest-version.yml/badge.svg" alt="D4L CI - Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-fhir-support.svg" alt="FHIR Support"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

The Data4Life FHIR SDK is an implementation of the HL7 FHIR Models for Kotlin. It supports encoding/decoding of FHIR data in JSON format.

=== Features

* Kotlin representation of FHIR resources, elements and primitives
* FHIR code systems are mostly represented as Enums
* Date/Time parsing, validation and (conversion Java Time / NSDate)
* JSON encoding/decoding

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]
* link:https://github.com/Kotlin/kotlinx.serialization[Kotlin Serialization]
* link:https://github.com/Kotlin/kotlinx-datetime[Kotlin DateTime]
* link:https://github.com/gesundheitscloud/fhir-parser[Python FHIR model generator]

== Getting Started

Instructions how to get software up and running.

=== Prerequisites

* link:https://developer.android.com/studio#downloads[Android Studio 4.2.1]
* link:https://adoptopenjdk.net/[Java 8] | link:https://developer.android.com/studio/write/java8-support[Limitations of Java language features and APIs] | https://jakewharton.com/d8-library-desugaring/[Desugaring]
* link:https://kotlinlang.org/[Kotlin 1.4.32]
* Android 6.0 (API 23) to Android 11.0 (API 30)

=== Installation

A step by step series of examples that tell you how to get it running.

==== Consume GitHub Packages

We use GitHub Packages to distribute the SDK. In order to consume our dependencies you need to generate a GitHub Personal Access Token. Please follow the how to link:https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages[authenticate to GitHub Packages, window="_blank"].

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo` and `read:packages` scope.

===== Token

The token needs to be made available.

. Add `gpr.user = {GitHub username}` and `gpr.key = {GitHub Personal Access Token}` to your global Gradle properties `~/.gradle/gradle.properties`

    gpr.user=github-username
    gpr.key=github-token

. Or add following environment variables `PACKAGE_REGISTRY_USERNAME={GitHub username}` and `PACKAGE_REGISTRY_TOKEN={GitHub Personal Access Token}`

===== Setup Maven Repository

Add the following maven repository configuration to your root build.gradle:

[source, Gradle]
----
    allprojects {
        repositories {
            ...
            maven {
                url = URI("https://maven.pkg.github.com/d4l-data4life/hc-fhir-sdk-kmp")
                credentials {
                    username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                    password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
                }
            }
        }
    }
----

== Usage

How to use this SDK.

=== Serialization

Create an instance of your desired `FhirStu3Parser` or `FhirR4Parser` using `FhirParserFactory.createStu3Parser()` or `FhirParserFactory.createR4Parser()`.

Decoding and Encoding JSON FHIR data is as simple as:

==== Decode

In case you know the type of FHIR JSON data, you could directly decode it.

[source, Kotlin]
----
val parser = FhirParserFactory.createR4Parser()

val data = parser.fromJson(DomainResource::class, "JSON FHIR data")
----

==== Encode

Just pass your FHIR data to the corresponding FHIR parser to encode to JSON format.

[source, Kotlin]
----
val parser = FhirParserFactory.createR4Parser()

val data = DomainResource()

val result = parser.toJson(data)

----

=== Model

FHIR Resources and Elements are represented as Kotlin interfaces which are named `Fhir` + ResourceType` e.g. `FhirDocumentReference`. While a `FhirDocumentReference` is implemented by `DocumentReference` which is a Kotlin data class. So they are equatable, copyable, destructable by default.

[source, Kotlin]
----
val name = HumanName(family = "Doe", given = listOf("John"))
val patient = Patient(name = listOf(name))

val newName = HumanName(family = "Doe", given = listOf("Jane"))
val patientCopy = patient.copy(name = listOf(newName))
----

If you need to access the FHIR `resourceType` from a given `class` or need to get the `class` for a given FHIR `resourceType` use the `FhirHelper.FhirElementFactory`:

[source, Kotlin]
----
val resourceType = FhirHelper.FhirElementFactory.getFhirResourceType(Patient::class)

val clazz = FhirHelper.FhirElementFactory.getFhirClass(resourceType)
----

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

Next planed features:

* add FHIR primitive extension support
* add more FHIR primitives
* add direct decoding from JSON without the need to pass in the correct type
* conversion to and from Java Time / NSDate
* write new FHIR generator
* add FHIR 5 once ready

Also see the open link:{link-repository}/issues[issues] for a list of proposed features and known issues.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.

Please refer to our link:LICENSE[License] for further details.

== Related Links

- link:http://hl7.org/fhir/index.html[FHIR current,window=_blank]
- link:http://hl7.org/fhir/STU3/index.html[FHIR 3 Overview,window=_blank] - link:http://hl7.org/fhir/STU3-3.0.1.zip[STU3-3.0.1.zip,window=_blank]
- link:http://hl7.org/fhir/R4/index.html[FHIR 4,window=_blank]
- link:https://github.com/gesundheitscloud/fhir-parser[Python FHIR model generator,window=_blank]
