/*
 * Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.hl7.fhir.r4.codesystem

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A code that indicates how the page is generated.
 *
 * @see <a href="http://hl7.org/fhir/guide-page-generation">GuidePageGeneration</a>
 * @see <a href="http://hl7.org/fhir/ValueSet/guide-page-generation">ValueSet</a>
 *
 * Generated from FHIR 4.0.1-9346c8cc45
 */
@Serializable
enum class GuidePageGeneration {

    /**
     * Page is proper xhtml with no templating.  Will be brought across unchanged for standard post-processing.
     */
    @SerialName("html")
    HTML,

    /**
     * Page is markdown with templating.  Will use the template to create a file that imports the markdown file prior to post-processing.
     */
    @SerialName("markdown")
    MARKDOWN,

    /**
     * Page is xml with templating.  Will use the template to create a file that imports the source file and run the nominated XSLT transform (see parameters) if present prior to post-processing.
     */
    @SerialName("xml")
    XML,

    /**
     * Page will be generated by the publication process - no source to bring across.
     */
    @SerialName("generated")
    GENERATED
}
