/*
 * Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.hl7.fhir.r4.model

import care.data4life.hl7.fhir.r4.FhirR4Parser
import care.data4life.hl7.fhir.r4.codesystem.ClaimProcessingCodes
import care.data4life.hl7.fhir.r4.codesystem.FinancialResourceStatusCodes
import care.data4life.hl7.fhir.r4.codesystem.NarrativeStatus
import care.data4life.hl7.fhir.r4.codesystem.NoteType
import care.data4life.hl7.fhir.r4.codesystem.Use
import care.data4life.hl7.fhir.test.util.FileHelper.loadAsString
import org.junit.Test
import org.skyscreamer.jsonassert.JSONAssert
import kotlin.test.assertEquals

/**
 * ClaimResponseTest.java
 *
 * Response to a claim predetermination or preauthorization
 *
 * This resource provides the adjudication details from the processing of a Claim resource.
 *
 * Generated from FHIR 4.0.1-9346c8cc45)
 */
@Suppress("UNNECESSARY_SAFE_CALL")
class ClaimResponseTest {

    val parser = FhirR4Parser()

    @Test
    fun testClaimResponse01() {
        // Given
        val sourceJson = loadAsString("r4/claimresponse-example-unsolicited-preauth.json")

        // When
        val data = parser.toFhir(ClaimResponse::class, sourceJson)

        // Then
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "250.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.addItem?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "10.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "copay",
            data.addItem?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.addItem?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "100.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(2)?.value?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(3)?.amount?.currency
        )
        assertEquals(
            "240.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(3)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.addItem?.get(0)?.adjudication?.get(3)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.addItem?.get(0)?.itemSequence?.get(0)?.value
        )
        assertEquals(
            "x",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.code
        )
        assertEquals(
            "None",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.display
        )
        assertEquals(
            "http://example.org/fhir/modifiers",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.net?.currency
        )
        assertEquals(
            "250.0".toDouble(),
            data.addItem?.get(0)?.net?.value?.value
        )
        assertEquals(
            "101".toLong(),
            data.addItem?.get(0)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "1101",
            data.addItem?.get(0)?.productOrService?.coding?.get(0)?.code
        )
        assertEquals(
            "http://example.org/fhir/oralservicecodes",
            data.addItem?.get(0)?.productOrService?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "800.0".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.addItem?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.addItem?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "100.0".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "800.0".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.addItem?.get(1)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.addItem?.get(1)?.itemSequence?.get(0)?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.net?.currency
        )
        assertEquals(
            "800.0".toDouble(),
            data.addItem?.get(1)?.net?.value?.value
        )
        assertEquals(
            "2101",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.code
        )
        assertEquals(
            "Radiograph, series (12)",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.display
        )
        assertEquals(
            "http://example.org/fhir/oralservicecodes",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.system
        )
        assertEquals(
            "2014-08-16",
            data.created?.value.toString()
        )
        assertEquals(
            "The enclosed services are authorized for your provision within 30 days of this notice.",
            data.disposition
        )
        assertEquals(
            "UR3503",
            data.id
        )
        assertEquals(
            "http://www.SocialBenefitsInc.com/fhir/ClaimResponse",
            data.identifier?.get(0)?.system
        )
        assertEquals(
            "UR3503",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "Coverage/9876B1",
            data.insurance?.get(0)?.coverage?.reference
        )
        assertEquals(
            "True".toBoolean(),
            data.insurance?.get(0)?.focal?.value
        )
        assertEquals(
            "1".toLong(),
            data.insurance?.get(0)?.sequence?.value
        )
        assertEquals(
            "http://www.jurisdiction.org/insurers",
            data.insurer?.identifier?.system
        )
        assertEquals(
            "444123",
            data.insurer?.identifier?.value
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            ClaimProcessingCodes.COMPLETE,
            data.outcome
        )
        assertEquals(
            "Patient/1",
            data.patient?.reference
        )
        assertEquals(
            "provider",
            data.payeeType?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/payeetype",
            data.payeeType?.coding?.get(0)?.system
        )
        assertEquals(
            "18SS12345",
            data.preAuthRef
        )
        assertEquals(
            "en-CA",
            data.processNote?.get(0)?.language?.coding?.get(0)?.code
        )
        assertEquals(
            "urn:ietf:bcp:47",
            data.processNote?.get(0)?.language?.coding?.get(0)?.system
        )
        assertEquals(
            "101".toLong(),
            data.processNote?.get(0)?.number?.value
        )
        assertEquals(
            "Please submit a Pre-Authorization request if a more extensive examination or urgent services are required.",
            data.processNote?.get(0)?.text
        )
        assertEquals(
            NoteType.PRINT,
            data.processNote?.get(0)?.type
        )
        assertEquals(
            "Organization/1",
            data.requestor?.reference
        )
        assertEquals(
            FinancialResourceStatusCodes.ACTIVE,
            data.status
        )
        assertEquals(
            "<div xmlns=\"http://www.w3.org/1999/xhtml\">A sample unsolicited pre-authorization response which authorizes basic dental services to be performed for a patient.</div>",
            data.text?.div
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            "USD",
            data.total?.get(0)?.amount?.currency
        )
        assertEquals(
            "1050.0".toDouble(),
            data.total?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "submitted",
            data.total?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.total?.get(1)?.amount?.currency
        )
        assertEquals(
            "1040.0".toDouble(),
            data.total?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.total?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "oral",
            data.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/claim-type",
            data.type?.coding?.get(0)?.system
        )
        assertEquals(
            Use.PREAUTHORIZATION,
            data.use
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testClaimResponse02() {
        // Given
        val sourceJson = loadAsString("r4/claimresponse-example-additem.json")

        // When
        val data = parser.toFhir(ClaimResponse::class, sourceJson)

        // Then
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "100.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.addItem?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "10.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "copay",
            data.addItem?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.addItem?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(2)?.value?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.adjudication?.get(3)?.amount?.currency
        )
        assertEquals(
            "72.0".toDouble(),
            data.addItem?.get(0)?.adjudication?.get(3)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.addItem?.get(0)?.adjudication?.get(3)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "ar002",
            data.addItem?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.code
        )
        assertEquals(
            "Plan Limit Reached",
            data.addItem?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/adjudication-reason",
            data.addItem?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.system
        )
        assertEquals(
            "1".toLong(),
            data.addItem?.get(0)?.itemSequence?.get(0)?.value
        )
        assertEquals(
            "x",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.code
        )
        assertEquals(
            "None",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.display
        )
        assertEquals(
            "http://example.org/fhir/modifiers",
            data.addItem?.get(0)?.modifier?.get(0)?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(0)?.net?.currency
        )
        assertEquals(
            "135.57".toDouble(),
            data.addItem?.get(0)?.net?.value?.value
        )
        assertEquals(
            "101".toLong(),
            data.addItem?.get(0)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "1101",
            data.addItem?.get(0)?.productOrService?.coding?.get(0)?.code
        )
        assertEquals(
            "http://example.org/fhir/oralservicecodes",
            data.addItem?.get(0)?.productOrService?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "35.57".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.addItem?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.addItem?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "28.47".toDouble(),
            data.addItem?.get(1)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.addItem?.get(1)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.addItem?.get(1)?.itemSequence?.get(0)?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(1)?.net?.currency
        )
        assertEquals(
            "35.57".toDouble(),
            data.addItem?.get(1)?.net?.value?.value
        )
        assertEquals(
            "2141",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.code
        )
        assertEquals(
            "Radiograph, bytewing",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.display
        )
        assertEquals(
            "http://example.org/fhir/oralservicecodes",
            data.addItem?.get(1)?.productOrService?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(2)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "350.0".toDouble(),
            data.addItem?.get(2)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.addItem?.get(2)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.addItem?.get(2)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.addItem?.get(2)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.addItem?.get(2)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "270.0".toDouble(),
            data.addItem?.get(2)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.addItem?.get(2)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "2".toLong(),
            data.addItem?.get(2)?.detailSequence?.get(0)?.value
        )
        assertEquals(
            "3".toLong(),
            data.addItem?.get(2)?.itemSequence?.get(0)?.value
        )
        assertEquals(
            "x",
            data.addItem?.get(2)?.modifier?.get(0)?.coding?.get(0)?.code
        )
        assertEquals(
            "None",
            data.addItem?.get(2)?.modifier?.get(0)?.coding?.get(0)?.display
        )
        assertEquals(
            "http://example.org/fhir/modifiers",
            data.addItem?.get(2)?.modifier?.get(0)?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.addItem?.get(2)?.net?.currency
        )
        assertEquals(
            "350.0".toDouble(),
            data.addItem?.get(2)?.net?.value?.value
        )
        assertEquals(
            "101".toLong(),
            data.addItem?.get(2)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "expense",
            data.addItem?.get(2)?.productOrService?.coding?.get(0)?.code
        )
        assertEquals(
            "http://example.org/fhir/oralservicecodes",
            data.addItem?.get(2)?.productOrService?.coding?.get(0)?.system
        )
        assertEquals(
            "2014-08-16",
            data.created?.value.toString()
        )
        assertEquals(
            "Claim settled as per contract.",
            data.disposition
        )
        assertEquals(
            "R3503",
            data.id
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/remittance",
            data.identifier?.get(0)?.system
        )
        assertEquals(
            "R3503",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "http://www.jurisdiction.org/insurers",
            data.insurer?.identifier?.system
        )
        assertEquals(
            "555123",
            data.insurer?.identifier?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "0.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "0.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.itemSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "105.0".toDouble(),
            data.item?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(1)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(1)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "84.0".toDouble(),
            data.item?.get(1)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(1)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "2".toLong(),
            data.item?.get(1)?.itemSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "750.0".toDouble(),
            data.item?.get(2)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(2)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(2)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(2)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "600.0".toDouble(),
            data.item?.get(2)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(2)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "750.0".toDouble(),
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "600.0".toDouble(),
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(2)?.detail?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(2)?.detail?.get(0)?.detailSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "0.0".toDouble(),
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "0.0".toDouble(),
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(2)?.detail?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "2".toLong(),
            data.item?.get(2)?.detail?.get(1)?.detailSequence?.value
        )
        assertEquals(
            "3".toLong(),
            data.item?.get(2)?.itemSequence?.value
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            ClaimProcessingCodes.COMPLETE,
            data.outcome
        )
        assertEquals(
            "Patient/1",
            data.patient?.reference
        )
        assertEquals(
            "provider",
            data.payeeType?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/payeetype",
            data.payeeType?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.payment?.amount?.currency
        )
        assertEquals(
            "100.47".toDouble(),
            data.payment?.amount?.value?.value
        )
        assertEquals(
            "2014-08-31",
            data.payment?.date?.value.toString()
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/paymentidentifier",
            data.payment?.identifier?.system
        )
        assertEquals(
            "201408-2-15507",
            data.payment?.identifier?.value
        )
        assertEquals(
            "complete",
            data.payment?.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/ex-paymenttype",
            data.payment?.type?.coding?.get(0)?.system
        )
        assertEquals(
            "en-CA",
            data.processNote?.get(0)?.language?.coding?.get(0)?.code
        )
        assertEquals(
            "urn:ietf:bcp:47",
            data.processNote?.get(0)?.language?.coding?.get(0)?.system
        )
        assertEquals(
            "101".toLong(),
            data.processNote?.get(0)?.number?.value
        )
        assertEquals(
            "Package codes are not permitted. Codes replaced by Insurer.",
            data.processNote?.get(0)?.text
        )
        assertEquals(
            NoteType.PRINT,
            data.processNote?.get(0)?.type
        )
        assertEquals(
            "http://happyvalley.com/claim",
            data.request?.identifier?.system
        )
        assertEquals(
            "12346",
            data.request?.identifier?.value
        )
        assertEquals(
            "Organization/1",
            data.requestor?.reference
        )
        assertEquals(
            FinancialResourceStatusCodes.ACTIVE,
            data.status
        )
        assertEquals(
            "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the ClaimResponse to Claim Oral Average with additional items</div>",
            data.text?.div
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            "USD",
            data.total?.get(0)?.amount?.currency
        )
        assertEquals(
            "1340.57".toDouble(),
            data.total?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "submitted",
            data.total?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.total?.get(1)?.amount?.currency
        )
        assertEquals(
            "1054.47".toDouble(),
            data.total?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.total?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "oral",
            data.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/claim-type",
            data.type?.coding?.get(0)?.system
        )
        assertEquals(
            Use.CLAIM,
            data.use
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testClaimResponse03() {
        // Given
        val sourceJson = loadAsString("r4/claimresponse-example.json")

        // When
        val data = parser.toFhir(ClaimResponse::class, sourceJson)

        // Then
        assertEquals(
            "2014-08-16",
            data.created?.value.toString()
        )
        assertEquals(
            "Claim settled as per contract.",
            data.disposition
        )
        assertEquals(
            "R3500",
            data.id
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/remittance",
            data.identifier?.get(0)?.system
        )
        assertEquals(
            "R3500",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "http://www.jurisdiction.org/insurers",
            data.insurer?.identifier?.system
        )
        assertEquals(
            "555123",
            data.insurer?.identifier?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "135.57".toDouble(),
            data.item?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "10.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "copay",
            data.item?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(2)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(3)?.amount?.currency
        )
        assertEquals(
            "90.47".toDouble(),
            data.item?.get(0)?.adjudication?.get(3)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.adjudication?.get(3)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "ar002",
            data.item?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.code
        )
        assertEquals(
            "Plan Limit Reached",
            data.item?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/adjudication-reason",
            data.item?.get(0)?.adjudication?.get(3)?.reason?.coding?.get(0)?.system
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.itemSequence?.value
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            ClaimProcessingCodes.COMPLETE,
            data.outcome
        )
        assertEquals(
            "Patient/1",
            data.patient?.reference
        )
        assertEquals(
            "provider",
            data.payeeType?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/payeetype",
            data.payeeType?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.payment?.amount?.currency
        )
        assertEquals(
            "100.47".toDouble(),
            data.payment?.amount?.value?.value
        )
        assertEquals(
            "2014-08-31",
            data.payment?.date?.value.toString()
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/paymentidentifier",
            data.payment?.identifier?.system
        )
        assertEquals(
            "201408-2-1569478",
            data.payment?.identifier?.value
        )
        assertEquals(
            "complete",
            data.payment?.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/ex-paymenttype",
            data.payment?.type?.coding?.get(0)?.system
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/oralhealthclaim/15476332402",
            data.request?.reference
        )
        assertEquals(
            "Organization/1",
            data.requestor?.reference
        )
        assertEquals(
            FinancialResourceStatusCodes.ACTIVE,
            data.status
        )
        assertEquals(
            "emergency",
            data.subType?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/ex-claimsubtype",
            data.subType?.coding?.get(0)?.system
        )
        assertEquals(
            "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the ClaimResponse</div>",
            data.text?.div
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            "USD",
            data.total?.get(0)?.amount?.currency
        )
        assertEquals(
            "135.57".toDouble(),
            data.total?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "submitted",
            data.total?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.total?.get(1)?.amount?.currency
        )
        assertEquals(
            "90.47".toDouble(),
            data.total?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.total?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "oral",
            data.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/claim-type",
            data.type?.coding?.get(0)?.system
        )
        assertEquals(
            Use.CLAIM,
            data.use
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testClaimResponse04() {
        // Given
        val sourceJson = loadAsString("r4/claimresponse-example-vision-3tier.json")

        // When
        val data = parser.toFhir(ClaimResponse::class, sourceJson)

        // Then
        assertEquals(
            "2014-08-16",
            data.created?.value.toString()
        )
        assertEquals(
            "Claim settled as per contract.",
            data.disposition
        )
        assertEquals(
            "R3502",
            data.id
        )
        assertEquals(
            "http://thebenefitcompany.com/claimresponse",
            data.identifier?.get(0)?.system
        )
        assertEquals(
            "CR6532875367",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "Organization/2",
            data.insurer?.reference
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "235.4".toDouble(),
            data.item?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "20.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "copay",
            data.item?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.adjudication?.get(2)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.adjudication?.get(3)?.amount?.currency
        )
        assertEquals(
            "172.32".toDouble(),
            data.item?.get(0)?.adjudication?.get(3)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.adjudication?.get(3)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "100.0".toDouble(),
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(1)?.amount?.currency
        )
        assertEquals(
            "20.0".toDouble(),
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "copay",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(2)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(3)?.amount?.currency
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(3)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(0)?.adjudication?.get(3)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(0)?.detailSequence?.value
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(0)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "110.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "88.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(1)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "2".toLong(),
            data.item?.get(0)?.detail?.get(1)?.detailSequence?.value
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(1)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "60.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "48.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(0)?.subDetailSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "30.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "24.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "2".toLong(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(1)?.subDetailSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "10.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "8.0".toDouble(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "3".toLong(),
            data.item?.get(0)?.detail?.get(1)?.subDetail?.get(2)?.subDetailSequence?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(0)?.amount?.currency
        )
        assertEquals(
            "200.0".toDouble(),
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "eligible",
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "eligpercent",
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "80.0".toDouble(),
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(1)?.value?.value
        )
        assertEquals(
            "USD",
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(2)?.amount?.currency
        )
        assertEquals(
            "14.0".toDouble(),
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(2)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.item?.get(0)?.detail?.get(2)?.adjudication?.get(2)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "3".toLong(),
            data.item?.get(0)?.detail?.get(2)?.detailSequence?.value
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.detail?.get(2)?.noteNumber?.get(0)?.value
        )
        assertEquals(
            "1".toLong(),
            data.item?.get(0)?.itemSequence?.value
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            ClaimProcessingCodes.COMPLETE,
            data.outcome
        )
        assertEquals(
            "Patient/1",
            data.patient?.reference
        )
        assertEquals(
            "provider",
            data.payeeType?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/payeetype",
            data.payeeType?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.payment?.adjustment?.currency
        )
        assertEquals(
            "75.0".toDouble(),
            data.payment?.adjustment?.value?.value
        )
        assertEquals(
            "a002",
            data.payment?.adjustmentReason?.coding?.get(0)?.code
        )
        assertEquals(
            "Prior Overpayment",
            data.payment?.adjustmentReason?.coding?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/payment-adjustment-reason",
            data.payment?.adjustmentReason?.coding?.get(0)?.system
        )
        assertEquals(
            "USD",
            data.payment?.amount?.currency
        )
        assertEquals(
            "107.0".toDouble(),
            data.payment?.amount?.value?.value
        )
        assertEquals(
            "2014-08-16",
            data.payment?.date?.value.toString()
        )
        assertEquals(
            "http://thebenefitcompany.com/paymentidentifier",
            data.payment?.identifier?.system
        )
        assertEquals(
            "201416-123456",
            data.payment?.identifier?.value
        )
        assertEquals(
            "complete",
            data.payment?.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/ex-paymenttype",
            data.payment?.type?.coding?.get(0)?.system
        )
        assertEquals(
            "en-CA",
            data.processNote?.get(0)?.language?.coding?.get(0)?.code
        )
        assertEquals(
            "urn:ietf:bcp:47",
            data.processNote?.get(0)?.language?.coding?.get(0)?.system
        )
        assertEquals(
            "1".toLong(),
            data.processNote?.get(0)?.number?.value
        )
        assertEquals(
            "After hours surcharge declined",
            data.processNote?.get(0)?.text
        )
        assertEquals(
            NoteType.DISPLAY,
            data.processNote?.get(0)?.type
        )
        assertEquals(
            "http://happysight.com/claim",
            data.request?.identifier?.system
        )
        assertEquals(
            "6612346",
            data.request?.identifier?.value
        )
        assertEquals(
            "Organization/1",
            data.requestor?.reference
        )
        assertEquals(
            FinancialResourceStatusCodes.ACTIVE,
            data.status
        )
        assertEquals(
            "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the ClaimResponse</div>",
            data.text?.div
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            "USD",
            data.total?.get(0)?.amount?.currency
        )
        assertEquals(
            "235.4".toDouble(),
            data.total?.get(0)?.amount?.value?.value
        )
        assertEquals(
            "submitted",
            data.total?.get(0)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "USD",
            data.total?.get(1)?.amount?.currency
        )
        assertEquals(
            "182.0".toDouble(),
            data.total?.get(1)?.amount?.value?.value
        )
        assertEquals(
            "benefit",
            data.total?.get(1)?.category?.coding?.get(0)?.code
        )
        assertEquals(
            "vision",
            data.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/claim-type",
            data.type?.coding?.get(0)?.system
        )
        assertEquals(
            Use.CLAIM,
            data.use
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testClaimResponse05() {
        // Given
        val sourceJson = loadAsString("r4/claimresponse-example-2.json")

        // When
        val data = parser.toFhir(ClaimResponse::class, sourceJson)

        // Then
        assertEquals(
            "CommunicationRequest/fm-solicit",
            data.communicationRequest?.get(0)?.reference
        )
        assertEquals(
            "2014-08-16",
            data.created?.value.toString()
        )
        assertEquals(
            "Claim could not be processed",
            data.disposition
        )
        assertEquals(
            "a002",
            data.error?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/adjudication-error",
            data.error?.get(0)?.code?.coding?.get(0)?.system
        )
        assertEquals(
            "2".toLong(),
            data.error?.get(0)?.detailSequence?.value
        )
        assertEquals(
            "3".toLong(),
            data.error?.get(0)?.itemSequence?.value
        )
        assertEquals(
            "2",
            data.formCode?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/forms-codes",
            data.formCode?.coding?.get(0)?.system
        )
        assertEquals(
            "R3501",
            data.id
        )
        assertEquals(
            "http://www.BenefitsInc.com/fhir/remittance",
            data.identifier?.get(0)?.system
        )
        assertEquals(
            "R3501",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "http://www.jurisdiction.org/insurers",
            data.insurer?.identifier?.system
        )
        assertEquals(
            "555123",
            data.insurer?.identifier?.value
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            ClaimProcessingCodes.ERROR,
            data.outcome
        )
        assertEquals(
            "Patient/1",
            data.patient?.reference
        )
        assertEquals(
            "en-CA",
            data.processNote?.get(0)?.language?.coding?.get(0)?.code
        )
        assertEquals(
            "urn:ietf:bcp:47",
            data.processNote?.get(0)?.language?.coding?.get(0)?.system
        )
        assertEquals(
            "1".toLong(),
            data.processNote?.get(0)?.number?.value
        )
        assertEquals(
            "Invalid claim",
            data.processNote?.get(0)?.text
        )
        assertEquals(
            NoteType.DISPLAY,
            data.processNote?.get(0)?.type
        )
        assertEquals(
            "Claim/100156",
            data.request?.reference
        )
        assertEquals(
            "Practitioner/1",
            data.requestor?.reference
        )
        assertEquals(
            FinancialResourceStatusCodes.ACTIVE,
            data.status
        )
        assertEquals(
            "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the ClaimResponse that demonstrates returning errors</div>",
            data.text?.div
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            "oral",
            data.type?.coding?.get(0)?.code
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/claim-type",
            data.type?.coding?.get(0)?.system
        )
        assertEquals(
            Use.CLAIM,
            data.use
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }
}
