/*
 * Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.hl7.fhir.r4.model

import care.data4life.hl7.fhir.r4.FhirR4Parser
import care.data4life.hl7.fhir.r4.codesystem.MeasureReportStatus
import care.data4life.hl7.fhir.r4.codesystem.MeasureReportType
import care.data4life.hl7.fhir.r4.codesystem.NarrativeStatus
import care.data4life.hl7.fhir.test.util.FileHelper.loadAsString
import org.junit.Test
import org.skyscreamer.jsonassert.JSONAssert
import kotlin.test.assertEquals

/**
 * MeasureReportTest.java
 *
 * Results of a measure evaluation
 *
 * The MeasureReport resource contains the results of the calculation of a measure; and optionally a
 * reference to the resources involved in that calculation.
 *
 * Generated from FHIR 4.0.1-9346c8cc45)
 */
@Suppress("UNNECESSARY_SAFE_CALL")
class MeasureReportTest {

    val parser = FhirR4Parser()

    @Test
    fun testMeasureReport01() {
        // Given
        val sourceJson = loadAsString("r4/measurereport-cms146-cat1-example.json")

        // When
        val data = parser.toFhir(MeasureReport::class, sourceJson)

        // Then
        assertEquals(
            "reporter",
            data.contained?.get(0)?.id
        )
        assertEquals(
            "2014-04-01",
            data.date?.value.toString()
        )
        assertEquals(
            "Condition/123",
            data.evaluatedResource?.get(0)?.reference
        )
        assertEquals(
            "CMS146-group-1",
            data.group?.get(0)?.id
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "stratifier-ages-up-to-9",
            data.group?.get(0)?.stratifier?.get(0)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-ages-10-plus",
            data.group?.get(0)?.stratifier?.get(1)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-gender",
            data.group?.get(0)?.stratifier?.get(2)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "1".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "male",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "female",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "other",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "unknown",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.value?.text
        )
        assertEquals(
            "measurereport-cms146-cat1-example",
            data.id
        )
        assertEquals(
            "measurereport-cms146-cat1-example-2017-03-13",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "Measure/CMS146",
            data.measure
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            "2014-03-31",
            data.period?.end?.value.toString()
        )
        assertEquals(
            "2014-01-01",
            data.period?.start?.value.toString()
        )
        assertEquals(
            "#reporter",
            data.reporter?.reference
        )
        assertEquals(
            MeasureReportStatus.COMPLETE,
            data.status
        )
        assertEquals(
            "Patient/123",
            data.subject?.reference
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            MeasureReportType.INDIVIDUAL,
            data.type
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testMeasureReport02() {
        // Given
        val sourceJson = loadAsString("r4/measurereport-cms146-cat2-example.json")

        // When
        val data = parser.toFhir(MeasureReport::class, sourceJson)

        // Then
        assertEquals(
            "reporter",
            data.contained?.get(0)?.id
        )
        assertEquals(
            "2014-04-01",
            data.date?.value.toString()
        )
        assertEquals(
            "CMS146-group-1",
            data.group?.get(0)?.id
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "500".toInt(),
            data.group?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-initial-population",
            data.group?.get(0)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "200".toInt(),
            data.group?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-numerator",
            data.group?.get(0)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "500".toInt(),
            data.group?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-denominator",
            data.group?.get(0)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-denominator-exclusions",
            data.group?.get(0)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "stratifier-ages-up-to-9",
            data.group?.get(0)?.stratifier?.get(0)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-true-initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-true-numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-true-denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-true-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-false-initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-false-numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-false-denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-up-to-9-false-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-ages-10-plus",
            data.group?.get(0)?.stratifier?.get(1)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-true-initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-true-numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-true-denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-true-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-false-initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-false-numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-false-denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-ages-10-plus-false-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-gender",
            data.group?.get(0)?.stratifier?.get(2)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-male-initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-male-numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-male-denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-male-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "male",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-female-initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-female-numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-female-denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-female-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "female",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-other-initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-other-numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-other-denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-other-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "other",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-unknown-initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.subjectResults?.reference
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-unknown-numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.subjectResults?.reference
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-unknown-denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.subjectResults?.reference
        )
        assertEquals(
            "denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "List/CMS146-stratifier-gender-unknown-denominator-exclusions",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.subjectResults?.reference
        )
        assertEquals(
            "unknown",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.value?.text
        )
        assertEquals(
            "measurereport-cms146-cat2-example",
            data.id
        )
        assertEquals(
            "measurereport-cms146-cat2-example-2017-03-13",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "Measure/CMS146",
            data.measure
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            "2014-03-31",
            data.period?.end?.value.toString()
        )
        assertEquals(
            "2014-01-01",
            data.period?.start?.value.toString()
        )
        assertEquals(
            "#reporter",
            data.reporter?.reference
        )
        assertEquals(
            MeasureReportStatus.COMPLETE,
            data.status
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            MeasureReportType.SUBJECT_LIST,
            data.type
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }

    @Test
    fun testMeasureReport03() {
        // Given
        val sourceJson = loadAsString("r4/measurereport-cms146-cat3-example.json")

        // When
        val data = parser.toFhir(MeasureReport::class, sourceJson)

        // Then
        assertEquals(
            "reporter",
            data.contained?.get(0)?.id
        )
        assertEquals(
            "2014-04-01",
            data.date?.value.toString()
        )
        assertEquals(
            "CMS146-group-1",
            data.group?.get(0)?.id
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "500".toInt(),
            data.group?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "200".toInt(),
            data.group?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "500".toInt(),
            data.group?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "stratifier-ages-up-to-9",
            data.group?.get(0)?.stratifier?.get(0)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(0)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-ages-10-plus",
            data.group?.get(0)?.stratifier?.get(1)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "true",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "false",
            data.group?.get(0)?.stratifier?.get(1)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "stratifier-gender",
            data.group?.get(0)?.stratifier?.get(2)?.code?.get(0)?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "male",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(0)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "100".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "250".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "50".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "female",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(1)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "other",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(2)?.value?.text
        )
        assertEquals(
            "initial-population",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(0)?.count?.value
        )
        assertEquals(
            "numerator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(1)?.count?.value
        )
        assertEquals(
            "denominator",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(2)?.count?.value
        )
        assertEquals(
            "denominator-exclusion",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.code?.coding?.get(0)?.code
        )
        assertEquals(
            "0".toInt(),
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.population?.get(3)?.count?.value
        )
        assertEquals(
            "unknown",
            data.group?.get(0)?.stratifier?.get(2)?.stratum?.get(3)?.value?.text
        )
        assertEquals(
            "measurereport-cms146-cat3-example",
            data.id
        )
        assertEquals(
            "measurereport-cms146-cat3-example-2017-03-13",
            data.identifier?.get(0)?.value
        )
        assertEquals(
            "Measure/CMS146",
            data.measure
        )
        assertEquals(
            "HTEST",
            data.meta?.tag?.get(0)?.code
        )
        assertEquals(
            "test health data",
            data.meta?.tag?.get(0)?.display
        )
        assertEquals(
            "http://terminology.hl7.org/CodeSystem/v3-ActReason",
            data.meta?.tag?.get(0)?.system
        )
        assertEquals(
            "2014-03-31",
            data.period?.end?.value.toString()
        )
        assertEquals(
            "2014-01-01",
            data.period?.start?.value.toString()
        )
        assertEquals(
            "#reporter",
            data.reporter?.reference
        )
        assertEquals(
            MeasureReportStatus.COMPLETE,
            data.status
        )
        assertEquals(
            NarrativeStatus.GENERATED,
            data.text?.status
        )
        assertEquals(
            MeasureReportType.SUMMARY,
            data.type
        )

        // When generating JSON from model
        val json = parser.fromFhir(data)

        // Then JSON needs to match original JSON file
        JSONAssert.assertEquals(sourceJson, json, true)
    }
}
