/*
 * Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.hl7.fhir.r4.model

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass
import kotlin.reflect.KClass

object FhirHelper {

    object FhirSerializationModule {
        fun module(): SerializersModule {
            return SerializersModule {
                polymorphic(FhirR4::class) {
                    subclass(Account::class)
                    subclass(AccountCoverage::class)
                    subclass(AccountGuarantor::class)
                    subclass(ActivityDefinition::class)
                    subclass(ActivityDefinitionDynamicValue::class)
                    subclass(ActivityDefinitionParticipant::class)
                    subclass(Address::class)
                    subclass(AdverseEvent::class)
                    subclass(AdverseEventSuspectEntity::class)
                    subclass(AdverseEventSuspectEntityCausality::class)
                    subclass(Age::class)
                    subclass(AllergyIntolerance::class)
                    subclass(AllergyIntoleranceReaction::class)
                    subclass(Annotation::class)
                    subclass(Appointment::class)
                    subclass(AppointmentParticipant::class)
                    subclass(AppointmentResponse::class)
                    subclass(Attachment::class)
                    subclass(AuditEvent::class)
                    subclass(AuditEventAgent::class)
                    subclass(AuditEventAgentNetwork::class)
                    subclass(AuditEventEntity::class)
                    subclass(AuditEventEntityDetail::class)
                    subclass(AuditEventSource::class)
                    subclass(BackboneElement::class)
                    subclass(Basic::class)
                    subclass(Binary::class)
                    subclass(BiologicallyDerivedProduct::class)
                    subclass(BiologicallyDerivedProductCollection::class)
                    subclass(BiologicallyDerivedProductManipulation::class)
                    subclass(BiologicallyDerivedProductProcessing::class)
                    subclass(BiologicallyDerivedProductStorage::class)
                    subclass(BodyStructure::class)
                    subclass(Bundle::class)
                    subclass(BundleEntry::class)
                    subclass(BundleEntryRequest::class)
                    subclass(BundleEntryResponse::class)
                    subclass(BundleEntrySearch::class)
                    subclass(BundleLink::class)
                    subclass(CapabilityStatement::class)
                    subclass(CapabilityStatementDocument::class)
                    subclass(CapabilityStatementImplementation::class)
                    subclass(CapabilityStatementMessaging::class)
                    subclass(CapabilityStatementMessagingEndpoint::class)
                    subclass(CapabilityStatementMessagingSupportedMessage::class)
                    subclass(CapabilityStatementRest::class)
                    subclass(CapabilityStatementRestInteraction::class)
                    subclass(CapabilityStatementRestResource::class)
                    subclass(CapabilityStatementRestResourceInteraction::class)
                    subclass(CapabilityStatementRestResourceOperation::class)
                    subclass(CapabilityStatementRestResourceSearchParam::class)
                    subclass(CapabilityStatementRestSecurity::class)
                    subclass(CapabilityStatementSoftware::class)
                    subclass(CarePlan::class)
                    subclass(CarePlanActivity::class)
                    subclass(CarePlanActivityDetail::class)
                    subclass(CareTeam::class)
                    subclass(CareTeamParticipant::class)
                    subclass(CatalogEntry::class)
                    subclass(CatalogEntryRelatedEntry::class)
                    subclass(ChargeItem::class)
                    subclass(ChargeItemDefinition::class)
                    subclass(ChargeItemDefinitionApplicability::class)
                    subclass(ChargeItemDefinitionPropertyGroup::class)
                    subclass(ChargeItemDefinitionPropertyGroupPriceComponent::class)
                    subclass(ChargeItemPerformer::class)
                    subclass(Claim::class)
                    subclass(ClaimAccident::class)
                    subclass(ClaimCareTeam::class)
                    subclass(ClaimDiagnosis::class)
                    subclass(ClaimInsurance::class)
                    subclass(ClaimItem::class)
                    subclass(ClaimItemDetail::class)
                    subclass(ClaimItemDetailSubDetail::class)
                    subclass(ClaimPayee::class)
                    subclass(ClaimProcedure::class)
                    subclass(ClaimRelated::class)
                    subclass(ClaimResponse::class)
                    subclass(ClaimResponseAddItem::class)
                    subclass(ClaimResponseAddItemDetail::class)
                    subclass(ClaimResponseAddItemDetailSubDetail::class)
                    subclass(ClaimResponseError::class)
                    subclass(ClaimResponseInsurance::class)
                    subclass(ClaimResponseItem::class)
                    subclass(ClaimResponseItemAdjudication::class)
                    subclass(ClaimResponseItemDetail::class)
                    subclass(ClaimResponseItemDetailSubDetail::class)
                    subclass(ClaimResponsePayment::class)
                    subclass(ClaimResponseProcessNote::class)
                    subclass(ClaimResponseTotal::class)
                    subclass(ClaimSupportingInfo::class)
                    subclass(ClinicalImpression::class)
                    subclass(ClinicalImpressionFinding::class)
                    subclass(ClinicalImpressionInvestigation::class)
                    subclass(CodeSystem::class)
                    subclass(CodeSystemConcept::class)
                    subclass(CodeSystemConceptDesignation::class)
                    subclass(CodeSystemConceptProperty::class)
                    subclass(CodeSystemFilter::class)
                    subclass(CodeSystemProperty::class)
                    subclass(CodeableConcept::class)
                    subclass(Coding::class)
                    subclass(Communication::class)
                    subclass(CommunicationPayload::class)
                    subclass(CommunicationRequest::class)
                    subclass(CommunicationRequestPayload::class)
                    subclass(CompartmentDefinition::class)
                    subclass(CompartmentDefinitionResource::class)
                    subclass(Composition::class)
                    subclass(CompositionAttester::class)
                    subclass(CompositionEvent::class)
                    subclass(CompositionRelatesTo::class)
                    subclass(CompositionSection::class)
                    subclass(ConceptMap::class)
                    subclass(ConceptMapGroup::class)
                    subclass(ConceptMapGroupElement::class)
                    subclass(ConceptMapGroupElementTarget::class)
                    subclass(ConceptMapGroupElementTargetDependsOn::class)
                    subclass(ConceptMapGroupUnmapped::class)
                    subclass(Condition::class)
                    subclass(ConditionEvidence::class)
                    subclass(ConditionStage::class)
                    subclass(Consent::class)
                    subclass(ConsentPolicy::class)
                    subclass(ConsentProvision::class)
                    subclass(ConsentProvisionActor::class)
                    subclass(ConsentProvisionData::class)
                    subclass(ConsentVerification::class)
                    subclass(ContactDetail::class)
                    subclass(ContactPoint::class)
                    subclass(Contract::class)
                    subclass(ContractContentDefinition::class)
                    subclass(ContractFriendly::class)
                    subclass(ContractLegal::class)
                    subclass(ContractRule::class)
                    subclass(ContractSigner::class)
                    subclass(ContractTerm::class)
                    subclass(ContractTermAction::class)
                    subclass(ContractTermActionSubject::class)
                    subclass(ContractTermAsset::class)
                    subclass(ContractTermAssetContext::class)
                    subclass(ContractTermAssetValuedItem::class)
                    subclass(ContractTermOffer::class)
                    subclass(ContractTermOfferAnswer::class)
                    subclass(ContractTermOfferParty::class)
                    subclass(ContractTermSecurityLabel::class)
                    subclass(Contributor::class)
                    subclass(Count::class)
                    subclass(Coverage::class)
                    subclass(CoverageClass::class)
                    subclass(CoverageCostToBeneficiary::class)
                    subclass(CoverageCostToBeneficiaryException::class)
                    subclass(CoverageEligibilityRequest::class)
                    subclass(CoverageEligibilityRequestInsurance::class)
                    subclass(CoverageEligibilityRequestItem::class)
                    subclass(CoverageEligibilityRequestItemDiagnosis::class)
                    subclass(CoverageEligibilityRequestSupportingInfo::class)
                    subclass(CoverageEligibilityResponse::class)
                    subclass(CoverageEligibilityResponseError::class)
                    subclass(CoverageEligibilityResponseInsurance::class)
                    subclass(CoverageEligibilityResponseInsuranceItem::class)
                    subclass(CoverageEligibilityResponseInsuranceItemBenefit::class)
                    subclass(DataRequirement::class)
                    subclass(DataRequirementCodeFilter::class)
                    subclass(DataRequirementDateFilter::class)
                    subclass(DataRequirementSort::class)
                    subclass(DetectedIssue::class)
                    subclass(DetectedIssueEvidence::class)
                    subclass(DetectedIssueMitigation::class)
                    subclass(Device::class)
                    subclass(DeviceDefinition::class)
                    subclass(DeviceDefinitionCapability::class)
                    subclass(DeviceDefinitionDeviceName::class)
                    subclass(DeviceDefinitionMaterial::class)
                    subclass(DeviceDefinitionProperty::class)
                    subclass(DeviceDefinitionSpecialization::class)
                    subclass(DeviceDefinitionUdiDeviceIdentifier::class)
                    subclass(DeviceDeviceName::class)
                    subclass(DeviceMetric::class)
                    subclass(DeviceMetricCalibration::class)
                    subclass(DeviceProperty::class)
                    subclass(DeviceRequest::class)
                    subclass(DeviceRequestParameter::class)
                    subclass(DeviceSpecialization::class)
                    subclass(DeviceUdiCarrier::class)
                    subclass(DeviceUseStatement::class)
                    subclass(DeviceVersion::class)
                    subclass(DiagnosticReport::class)
                    subclass(DiagnosticReportMedia::class)
                    subclass(Distance::class)
                    subclass(DocumentManifest::class)
                    subclass(DocumentManifestRelated::class)
                    subclass(DocumentReference::class)
                    subclass(DocumentReferenceContent::class)
                    subclass(DocumentReferenceContext::class)
                    subclass(DocumentReferenceRelatesTo::class)
                    subclass(DomainResource::class)
                    subclass(Dosage::class)
                    subclass(DosageDoseAndRate::class)
                    subclass(Duration::class)
                    subclass(EffectEvidenceSynthesis::class)
                    subclass(EffectEvidenceSynthesisCertainty::class)
                    subclass(EffectEvidenceSynthesisCertaintyCertaintySubcomponent::class)
                    subclass(EffectEvidenceSynthesisEffectEstimate::class)
                    subclass(EffectEvidenceSynthesisEffectEstimatePrecisionEstimate::class)
                    subclass(EffectEvidenceSynthesisResultsByExposure::class)
                    subclass(EffectEvidenceSynthesisSampleSize::class)
                    subclass(Element::class)
                    subclass(ElementDefinition::class)
                    subclass(ElementDefinitionBase::class)
                    subclass(ElementDefinitionBinding::class)
                    subclass(ElementDefinitionConstraint::class)
                    subclass(ElementDefinitionExample::class)
                    subclass(ElementDefinitionMapping::class)
                    subclass(ElementDefinitionSlicing::class)
                    subclass(ElementDefinitionSlicingDiscriminator::class)
                    subclass(ElementDefinitionType::class)
                    subclass(Encounter::class)
                    subclass(EncounterClassHistory::class)
                    subclass(EncounterDiagnosis::class)
                    subclass(EncounterHospitalization::class)
                    subclass(EncounterLocation::class)
                    subclass(EncounterParticipant::class)
                    subclass(EncounterStatusHistory::class)
                    subclass(Endpoint::class)
                    subclass(EnrollmentRequest::class)
                    subclass(EnrollmentResponse::class)
                    subclass(EpisodeOfCare::class)
                    subclass(EpisodeOfCareDiagnosis::class)
                    subclass(EpisodeOfCareStatusHistory::class)
                    subclass(EventDefinition::class)
                    subclass(Evidence::class)
                    subclass(EvidenceVariable::class)
                    subclass(EvidenceVariableCharacteristic::class)
                    subclass(ExplanationOfBenefit::class)
                    subclass(ExplanationOfBenefitAccident::class)
                    subclass(ExplanationOfBenefitAddItem::class)
                    subclass(ExplanationOfBenefitAddItemDetail::class)
                    subclass(ExplanationOfBenefitAddItemDetailSubDetail::class)
                    subclass(ExplanationOfBenefitBenefitBalance::class)
                    subclass(ExplanationOfBenefitBenefitBalanceFinancial::class)
                    subclass(ExplanationOfBenefitCareTeam::class)
                    subclass(ExplanationOfBenefitDiagnosis::class)
                    subclass(ExplanationOfBenefitInsurance::class)
                    subclass(ExplanationOfBenefitItem::class)
                    subclass(ExplanationOfBenefitItemAdjudication::class)
                    subclass(ExplanationOfBenefitItemDetail::class)
                    subclass(ExplanationOfBenefitItemDetailSubDetail::class)
                    subclass(ExplanationOfBenefitPayee::class)
                    subclass(ExplanationOfBenefitPayment::class)
                    subclass(ExplanationOfBenefitProcedure::class)
                    subclass(ExplanationOfBenefitProcessNote::class)
                    subclass(ExplanationOfBenefitRelated::class)
                    subclass(ExplanationOfBenefitSupportingInfo::class)
                    subclass(ExplanationOfBenefitTotal::class)
                    subclass(Expression::class)
                    subclass(Extension::class)
                    subclass(FamilyMemberHistory::class)
                    subclass(FamilyMemberHistoryCondition::class)
                    subclass(Flag::class)
                    subclass(Goal::class)
                    subclass(GoalTarget::class)
                    subclass(GraphDefinition::class)
                    subclass(GraphDefinitionLink::class)
                    subclass(GraphDefinitionLinkTarget::class)
                    subclass(GraphDefinitionLinkTargetCompartment::class)
                    subclass(Group::class)
                    subclass(GroupCharacteristic::class)
                    subclass(GroupMember::class)
                    subclass(GuidanceResponse::class)
                    subclass(HealthcareService::class)
                    subclass(HealthcareServiceAvailableTime::class)
                    subclass(HealthcareServiceEligibility::class)
                    subclass(HealthcareServiceNotAvailable::class)
                    subclass(HumanName::class)
                    subclass(Identifier::class)
                    subclass(ImagingStudy::class)
                    subclass(ImagingStudySeries::class)
                    subclass(ImagingStudySeriesInstance::class)
                    subclass(ImagingStudySeriesPerformer::class)
                    subclass(Immunization::class)
                    subclass(ImmunizationEducation::class)
                    subclass(ImmunizationEvaluation::class)
                    subclass(ImmunizationPerformer::class)
                    subclass(ImmunizationProtocolApplied::class)
                    subclass(ImmunizationReaction::class)
                    subclass(ImmunizationRecommendation::class)
                    subclass(ImmunizationRecommendationRecommendation::class)
                    subclass(ImmunizationRecommendationRecommendationDateCriterion::class)
                    subclass(ImplementationGuide::class)
                    subclass(ImplementationGuideDefinition::class)
                    subclass(ImplementationGuideDefinitionGrouping::class)
                    subclass(ImplementationGuideDefinitionPage::class)
                    subclass(ImplementationGuideDefinitionParameter::class)
                    subclass(ImplementationGuideDefinitionResource::class)
                    subclass(ImplementationGuideDefinitionTemplate::class)
                    subclass(ImplementationGuideDependsOn::class)
                    subclass(ImplementationGuideGlobal::class)
                    subclass(ImplementationGuideManifest::class)
                    subclass(ImplementationGuideManifestPage::class)
                    subclass(ImplementationGuideManifestResource::class)
                    subclass(InsurancePlan::class)
                    subclass(InsurancePlanContact::class)
                    subclass(InsurancePlanCoverage::class)
                    subclass(InsurancePlanCoverageBenefit::class)
                    subclass(InsurancePlanCoverageBenefitLimit::class)
                    subclass(InsurancePlanPlan::class)
                    subclass(InsurancePlanPlanGeneralCost::class)
                    subclass(InsurancePlanPlanSpecificCost::class)
                    subclass(InsurancePlanPlanSpecificCostBenefit::class)
                    subclass(InsurancePlanPlanSpecificCostBenefitCost::class)
                    subclass(Invoice::class)
                    subclass(InvoiceLineItem::class)
                    subclass(InvoiceLineItemPriceComponent::class)
                    subclass(InvoiceParticipant::class)
                    subclass(Library::class)
                    subclass(Linkage::class)
                    subclass(LinkageItem::class)
                    subclass(List::class)
                    subclass(ListEntry::class)
                    subclass(Location::class)
                    subclass(LocationHoursOfOperation::class)
                    subclass(LocationPosition::class)
                    subclass(MarketingStatus::class)
                    subclass(Measure::class)
                    subclass(MeasureGroup::class)
                    subclass(MeasureGroupPopulation::class)
                    subclass(MeasureGroupStratifier::class)
                    subclass(MeasureGroupStratifierComponent::class)
                    subclass(MeasureReport::class)
                    subclass(MeasureReportGroup::class)
                    subclass(MeasureReportGroupPopulation::class)
                    subclass(MeasureReportGroupStratifier::class)
                    subclass(MeasureReportGroupStratifierStratum::class)
                    subclass(MeasureReportGroupStratifierStratumComponent::class)
                    subclass(MeasureReportGroupStratifierStratumPopulation::class)
                    subclass(MeasureSupplementalData::class)
                    subclass(Media::class)
                    subclass(Medication::class)
                    subclass(MedicationAdministration::class)
                    subclass(MedicationAdministrationDosage::class)
                    subclass(MedicationAdministrationPerformer::class)
                    subclass(MedicationBatch::class)
                    subclass(MedicationDispense::class)
                    subclass(MedicationDispensePerformer::class)
                    subclass(MedicationDispenseSubstitution::class)
                    subclass(MedicationIngredient::class)
                    subclass(MedicationKnowledge::class)
                    subclass(MedicationKnowledgeAdministrationGuidelines::class)
                    subclass(MedicationKnowledgeAdministrationGuidelinesDosage::class)
                    subclass(MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics::class)
                    subclass(MedicationKnowledgeCost::class)
                    subclass(MedicationKnowledgeDrugCharacteristic::class)
                    subclass(MedicationKnowledgeIngredient::class)
                    subclass(MedicationKnowledgeKinetics::class)
                    subclass(MedicationKnowledgeMedicineClassification::class)
                    subclass(MedicationKnowledgeMonitoringProgram::class)
                    subclass(MedicationKnowledgeMonograph::class)
                    subclass(MedicationKnowledgePackaging::class)
                    subclass(MedicationKnowledgeRegulatory::class)
                    subclass(MedicationKnowledgeRegulatoryMaxDispense::class)
                    subclass(MedicationKnowledgeRegulatorySchedule::class)
                    subclass(MedicationKnowledgeRegulatorySubstitution::class)
                    subclass(MedicationKnowledgeRelatedMedicationKnowledge::class)
                    subclass(MedicationRequest::class)
                    subclass(MedicationRequestDispenseRequest::class)
                    subclass(MedicationRequestDispenseRequestInitialFill::class)
                    subclass(MedicationRequestSubstitution::class)
                    subclass(MedicationStatement::class)
                    subclass(MedicinalProduct::class)
                    subclass(MedicinalProductAuthorization::class)
                    subclass(MedicinalProductAuthorizationJurisdictionalAuthorization::class)
                    subclass(MedicinalProductAuthorizationProcedure::class)
                    subclass(MedicinalProductContraindication::class)
                    subclass(MedicinalProductContraindicationOtherTherapy::class)
                    subclass(MedicinalProductIndication::class)
                    subclass(MedicinalProductIndicationOtherTherapy::class)
                    subclass(MedicinalProductIngredient::class)
                    subclass(MedicinalProductIngredientSpecifiedSubstance::class)
                    subclass(MedicinalProductIngredientSpecifiedSubstanceStrength::class)
                    subclass(MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength::class)
                    subclass(MedicinalProductIngredientSubstance::class)
                    subclass(MedicinalProductInteraction::class)
                    subclass(MedicinalProductInteractionInteractant::class)
                    subclass(MedicinalProductManufactured::class)
                    subclass(MedicinalProductManufacturingBusinessOperation::class)
                    subclass(MedicinalProductName::class)
                    subclass(MedicinalProductNameCountryLanguage::class)
                    subclass(MedicinalProductNameNamePart::class)
                    subclass(MedicinalProductPackaged::class)
                    subclass(MedicinalProductPackagedBatchIdentifier::class)
                    subclass(MedicinalProductPackagedPackageItem::class)
                    subclass(MedicinalProductPharmaceutical::class)
                    subclass(MedicinalProductPharmaceuticalCharacteristics::class)
                    subclass(MedicinalProductPharmaceuticalRouteOfAdministration::class)
                    subclass(MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies::class)
                    subclass(MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod::class)
                    subclass(MedicinalProductSpecialDesignation::class)
                    subclass(MedicinalProductUndesirableEffect::class)
                    subclass(MessageDefinition::class)
                    subclass(MessageDefinitionAllowedResponse::class)
                    subclass(MessageDefinitionFocus::class)
                    subclass(MessageHeader::class)
                    subclass(MessageHeaderDestination::class)
                    subclass(MessageHeaderResponse::class)
                    subclass(MessageHeaderSource::class)
                    subclass(Meta::class)
                    subclass(MetadataResource::class)
                    subclass(MolecularSequence::class)
                    subclass(MolecularSequenceQuality::class)
                    subclass(MolecularSequenceQualityRoc::class)
                    subclass(MolecularSequenceReferenceSeq::class)
                    subclass(MolecularSequenceRepository::class)
                    subclass(MolecularSequenceStructureVariant::class)
                    subclass(MolecularSequenceStructureVariantInner::class)
                    subclass(MolecularSequenceStructureVariantOuter::class)
                    subclass(MolecularSequenceVariant::class)
                    subclass(Money::class)
                    subclass(NamingSystem::class)
                    subclass(NamingSystemUniqueId::class)
                    subclass(Narrative::class)
                    subclass(NutritionOrder::class)
                    subclass(NutritionOrderEnteralFormula::class)
                    subclass(NutritionOrderEnteralFormulaAdministration::class)
                    subclass(NutritionOrderOralDiet::class)
                    subclass(NutritionOrderOralDietNutrient::class)
                    subclass(NutritionOrderOralDietTexture::class)
                    subclass(NutritionOrderSupplement::class)
                    subclass(Observation::class)
                    subclass(ObservationComponent::class)
                    subclass(ObservationDefinition::class)
                    subclass(ObservationDefinitionQualifiedInterval::class)
                    subclass(ObservationDefinitionQuantitativeDetails::class)
                    subclass(ObservationReferenceRange::class)
                    subclass(OperationDefinition::class)
                    subclass(OperationDefinitionOverload::class)
                    subclass(OperationDefinitionParameter::class)
                    subclass(OperationDefinitionParameterBinding::class)
                    subclass(OperationDefinitionParameterReferencedFrom::class)
                    subclass(OperationOutcome::class)
                    subclass(OperationOutcomeIssue::class)
                    subclass(Organization::class)
                    subclass(OrganizationAffiliation::class)
                    subclass(OrganizationContact::class)
                    subclass(ParameterDefinition::class)
                    subclass(Parameters::class)
                    subclass(ParametersParameter::class)
                    subclass(Patient::class)
                    subclass(PatientCommunication::class)
                    subclass(PatientContact::class)
                    subclass(PatientLink::class)
                    subclass(PaymentNotice::class)
                    subclass(PaymentReconciliation::class)
                    subclass(PaymentReconciliationDetail::class)
                    subclass(PaymentReconciliationProcessNote::class)
                    subclass(Period::class)
                    subclass(Person::class)
                    subclass(PersonLink::class)
                    subclass(PlanDefinition::class)
                    subclass(PlanDefinitionAction::class)
                    subclass(PlanDefinitionActionCondition::class)
                    subclass(PlanDefinitionActionDynamicValue::class)
                    subclass(PlanDefinitionActionParticipant::class)
                    subclass(PlanDefinitionActionRelatedAction::class)
                    subclass(PlanDefinitionGoal::class)
                    subclass(PlanDefinitionGoalTarget::class)
                    subclass(Population::class)
                    subclass(Practitioner::class)
                    subclass(PractitionerQualification::class)
                    subclass(PractitionerRole::class)
                    subclass(PractitionerRoleAvailableTime::class)
                    subclass(PractitionerRoleNotAvailable::class)
                    subclass(Procedure::class)
                    subclass(ProcedureFocalDevice::class)
                    subclass(ProcedurePerformer::class)
                    subclass(ProdCharacteristic::class)
                    subclass(ProductShelfLife::class)
                    subclass(Provenance::class)
                    subclass(ProvenanceAgent::class)
                    subclass(ProvenanceEntity::class)
                    subclass(Quantity::class)
                    subclass(Quantity::class)
                    subclass(Questionnaire::class)
                    subclass(QuestionnaireItem::class)
                    subclass(QuestionnaireItemAnswerOption::class)
                    subclass(QuestionnaireItemEnableWhen::class)
                    subclass(QuestionnaireItemInitial::class)
                    subclass(QuestionnaireResponse::class)
                    subclass(QuestionnaireResponseItem::class)
                    subclass(QuestionnaireResponseItemAnswer::class)
                    subclass(Range::class)
                    subclass(Ratio::class)
                    subclass(Reference::class)
                    subclass(RelatedArtifact::class)
                    subclass(RelatedPerson::class)
                    subclass(RelatedPersonCommunication::class)
                    subclass(RequestGroup::class)
                    subclass(RequestGroupAction::class)
                    subclass(RequestGroupActionCondition::class)
                    subclass(RequestGroupActionRelatedAction::class)
                    subclass(ResearchDefinition::class)
                    subclass(ResearchElementDefinition::class)
                    subclass(ResearchElementDefinitionCharacteristic::class)
                    subclass(ResearchStudy::class)
                    subclass(ResearchStudyArm::class)
                    subclass(ResearchStudyObjective::class)
                    subclass(ResearchSubject::class)
                    subclass(Resource::class)
                    subclass(RiskAssessment::class)
                    subclass(RiskAssessmentPrediction::class)
                    subclass(RiskEvidenceSynthesis::class)
                    subclass(RiskEvidenceSynthesisCertainty::class)
                    subclass(RiskEvidenceSynthesisCertaintyCertaintySubcomponent::class)
                    subclass(RiskEvidenceSynthesisRiskEstimate::class)
                    subclass(RiskEvidenceSynthesisRiskEstimatePrecisionEstimate::class)
                    subclass(RiskEvidenceSynthesisSampleSize::class)
                    subclass(SampledData::class)
                    subclass(Schedule::class)
                    subclass(SearchParameter::class)
                    subclass(SearchParameterComponent::class)
                    subclass(ServiceRequest::class)
                    subclass(Signature::class)
                    subclass(Slot::class)
                    subclass(Specimen::class)
                    subclass(SpecimenCollection::class)
                    subclass(SpecimenContainer::class)
                    subclass(SpecimenDefinition::class)
                    subclass(SpecimenDefinitionTypeTested::class)
                    subclass(SpecimenDefinitionTypeTestedContainer::class)
                    subclass(SpecimenDefinitionTypeTestedContainerAdditive::class)
                    subclass(SpecimenDefinitionTypeTestedHandling::class)
                    subclass(SpecimenProcessing::class)
                    subclass(StructureDefinition::class)
                    subclass(StructureDefinitionContext::class)
                    subclass(StructureDefinitionDifferential::class)
                    subclass(StructureDefinitionMapping::class)
                    subclass(StructureDefinitionSnapshot::class)
                    subclass(StructureMap::class)
                    subclass(StructureMapGroup::class)
                    subclass(StructureMapGroupInput::class)
                    subclass(StructureMapGroupRule::class)
                    subclass(StructureMapGroupRuleDependent::class)
                    subclass(StructureMapGroupRuleSource::class)
                    subclass(StructureMapGroupRuleTarget::class)
                    subclass(StructureMapGroupRuleTargetParameter::class)
                    subclass(StructureMapStructure::class)
                    subclass(Subscription::class)
                    subclass(SubscriptionChannel::class)
                    subclass(Substance::class)
                    subclass(SubstanceAmount::class)
                    subclass(SubstanceAmountReferenceRange::class)
                    subclass(SubstanceIngredient::class)
                    subclass(SubstanceInstance::class)
                    subclass(SubstanceNucleicAcid::class)
                    subclass(SubstanceNucleicAcidSubunit::class)
                    subclass(SubstanceNucleicAcidSubunitLinkage::class)
                    subclass(SubstanceNucleicAcidSubunitSugar::class)
                    subclass(SubstancePolymer::class)
                    subclass(SubstancePolymerMonomerSet::class)
                    subclass(SubstancePolymerMonomerSetStartingMaterial::class)
                    subclass(SubstancePolymerRepeat::class)
                    subclass(SubstancePolymerRepeatRepeatUnit::class)
                    subclass(SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation::class)
                    subclass(SubstancePolymerRepeatRepeatUnitStructuralRepresentation::class)
                    subclass(SubstanceProtein::class)
                    subclass(SubstanceProteinSubunit::class)
                    subclass(SubstanceReferenceInformation::class)
                    subclass(SubstanceReferenceInformationClassification::class)
                    subclass(SubstanceReferenceInformationGene::class)
                    subclass(SubstanceReferenceInformationGeneElement::class)
                    subclass(SubstanceReferenceInformationTarget::class)
                    subclass(SubstanceSourceMaterial::class)
                    subclass(SubstanceSourceMaterialFractionDescription::class)
                    subclass(SubstanceSourceMaterialOrganism::class)
                    subclass(SubstanceSourceMaterialOrganismAuthor::class)
                    subclass(SubstanceSourceMaterialOrganismHybrid::class)
                    subclass(SubstanceSourceMaterialOrganismOrganismGeneral::class)
                    subclass(SubstanceSourceMaterialPartDescription::class)
                    subclass(SubstanceSpecification::class)
                    subclass(SubstanceSpecificationMoiety::class)
                    subclass(SubstanceSpecificationName::class)
                    subclass(SubstanceSpecificationNameOfficial::class)
                    subclass(SubstanceSpecificationProperty::class)
                    subclass(SubstanceSpecificationRelationship::class)
                    subclass(SubstanceSpecificationString::class)
                    subclass(SubstanceSpecificationStructure::class)
                    subclass(SubstanceSpecificationStructureIsotope::class)
                    subclass(SubstanceSpecificationStructureIsotopeMolecularWeight::class)
                    subclass(SubstanceSpecificationStructureRepresentation::class)
                    subclass(SupplyDelivery::class)
                    subclass(SupplyDeliverySuppliedItem::class)
                    subclass(SupplyRequest::class)
                    subclass(SupplyRequestParameter::class)
                    subclass(Task::class)
                    subclass(TaskInput::class)
                    subclass(TaskOutput::class)
                    subclass(TaskRestriction::class)
                    subclass(TerminologyCapabilities::class)
                    subclass(TerminologyCapabilitiesClosure::class)
                    subclass(TerminologyCapabilitiesCodeSystem::class)
                    subclass(TerminologyCapabilitiesCodeSystemVersion::class)
                    subclass(TerminologyCapabilitiesCodeSystemVersionFilter::class)
                    subclass(TerminologyCapabilitiesExpansion::class)
                    subclass(TerminologyCapabilitiesExpansionParameter::class)
                    subclass(TerminologyCapabilitiesImplementation::class)
                    subclass(TerminologyCapabilitiesSoftware::class)
                    subclass(TerminologyCapabilitiesTranslation::class)
                    subclass(TerminologyCapabilitiesValidateCode::class)
                    subclass(TestReport::class)
                    subclass(TestReportParticipant::class)
                    subclass(TestReportSetup::class)
                    subclass(TestReportSetupAction::class)
                    subclass(TestReportSetupActionAssert::class)
                    subclass(TestReportSetupActionOperation::class)
                    subclass(TestReportTeardown::class)
                    subclass(TestReportTeardownAction::class)
                    subclass(TestReportTest::class)
                    subclass(TestReportTestAction::class)
                    subclass(TestScript::class)
                    subclass(TestScriptDestination::class)
                    subclass(TestScriptFixture::class)
                    subclass(TestScriptMetadata::class)
                    subclass(TestScriptMetadataCapability::class)
                    subclass(TestScriptMetadataLink::class)
                    subclass(TestScriptOrigin::class)
                    subclass(TestScriptSetup::class)
                    subclass(TestScriptSetupAction::class)
                    subclass(TestScriptSetupActionAssert::class)
                    subclass(TestScriptSetupActionOperation::class)
                    subclass(TestScriptSetupActionOperationRequestHeader::class)
                    subclass(TestScriptTeardown::class)
                    subclass(TestScriptTeardownAction::class)
                    subclass(TestScriptTest::class)
                    subclass(TestScriptTestAction::class)
                    subclass(TestScriptVariable::class)
                    subclass(Timing::class)
                    subclass(TimingRepeat::class)
                    subclass(TriggerDefinition::class)
                    subclass(UsageContext::class)
                    subclass(ValueSet::class)
                    subclass(ValueSetCompose::class)
                    subclass(ValueSetComposeInclude::class)
                    subclass(ValueSetComposeIncludeConcept::class)
                    subclass(ValueSetComposeIncludeConceptDesignation::class)
                    subclass(ValueSetComposeIncludeFilter::class)
                    subclass(ValueSetExpansion::class)
                    subclass(ValueSetExpansionContains::class)
                    subclass(ValueSetExpansionParameter::class)
                    subclass(VerificationResult::class)
                    subclass(VerificationResultAttestation::class)
                    subclass(VerificationResultPrimarySource::class)
                    subclass(VerificationResultValidator::class)
                    subclass(VisionPrescription::class)
                    subclass(VisionPrescriptionLensSpecification::class)
                    subclass(VisionPrescriptionLensSpecificationPrism::class)
                }
                polymorphic(FhirResource::class) {
                    subclass(Account::class)
                    subclass(ActivityDefinition::class)
                    subclass(AdverseEvent::class)
                    subclass(AllergyIntolerance::class)
                    subclass(Appointment::class)
                    subclass(AppointmentResponse::class)
                    subclass(AuditEvent::class)
                    subclass(Basic::class)
                    subclass(Binary::class)
                    subclass(BiologicallyDerivedProduct::class)
                    subclass(BodyStructure::class)
                    subclass(Bundle::class)
                    subclass(CapabilityStatement::class)
                    subclass(CarePlan::class)
                    subclass(CareTeam::class)
                    subclass(CatalogEntry::class)
                    subclass(ChargeItem::class)
                    subclass(ChargeItemDefinition::class)
                    subclass(Claim::class)
                    subclass(ClaimResponse::class)
                    subclass(ClinicalImpression::class)
                    subclass(CodeSystem::class)
                    subclass(Communication::class)
                    subclass(CommunicationRequest::class)
                    subclass(CompartmentDefinition::class)
                    subclass(Composition::class)
                    subclass(ConceptMap::class)
                    subclass(Condition::class)
                    subclass(Consent::class)
                    subclass(Contract::class)
                    subclass(Coverage::class)
                    subclass(CoverageEligibilityRequest::class)
                    subclass(CoverageEligibilityResponse::class)
                    subclass(DetectedIssue::class)
                    subclass(Device::class)
                    subclass(DeviceDefinition::class)
                    subclass(DeviceMetric::class)
                    subclass(DeviceRequest::class)
                    subclass(DeviceUseStatement::class)
                    subclass(DiagnosticReport::class)
                    subclass(DocumentManifest::class)
                    subclass(DocumentReference::class)
                    subclass(DomainResource::class)
                    subclass(EffectEvidenceSynthesis::class)
                    subclass(Encounter::class)
                    subclass(Endpoint::class)
                    subclass(EnrollmentRequest::class)
                    subclass(EnrollmentResponse::class)
                    subclass(EpisodeOfCare::class)
                    subclass(EventDefinition::class)
                    subclass(Evidence::class)
                    subclass(EvidenceVariable::class)
                    subclass(ExplanationOfBenefit::class)
                    subclass(FamilyMemberHistory::class)
                    subclass(Flag::class)
                    subclass(Goal::class)
                    subclass(GraphDefinition::class)
                    subclass(Group::class)
                    subclass(GuidanceResponse::class)
                    subclass(HealthcareService::class)
                    subclass(ImagingStudy::class)
                    subclass(Immunization::class)
                    subclass(ImmunizationEvaluation::class)
                    subclass(ImmunizationRecommendation::class)
                    subclass(ImplementationGuide::class)
                    subclass(InsurancePlan::class)
                    subclass(Invoice::class)
                    subclass(Library::class)
                    subclass(Linkage::class)
                    subclass(List::class)
                    subclass(Location::class)
                    subclass(Measure::class)
                    subclass(MeasureReport::class)
                    subclass(Media::class)
                    subclass(Medication::class)
                    subclass(MedicationAdministration::class)
                    subclass(MedicationDispense::class)
                    subclass(MedicationKnowledge::class)
                    subclass(MedicationRequest::class)
                    subclass(MedicationStatement::class)
                    subclass(MedicinalProduct::class)
                    subclass(MedicinalProductAuthorization::class)
                    subclass(MedicinalProductContraindication::class)
                    subclass(MedicinalProductIndication::class)
                    subclass(MedicinalProductIngredient::class)
                    subclass(MedicinalProductInteraction::class)
                    subclass(MedicinalProductManufactured::class)
                    subclass(MedicinalProductPackaged::class)
                    subclass(MedicinalProductPharmaceutical::class)
                    subclass(MedicinalProductUndesirableEffect::class)
                    subclass(MessageDefinition::class)
                    subclass(MessageHeader::class)
                    subclass(MolecularSequence::class)
                    subclass(NamingSystem::class)
                    subclass(NutritionOrder::class)
                    subclass(Observation::class)
                    subclass(ObservationDefinition::class)
                    subclass(OperationDefinition::class)
                    subclass(OperationOutcome::class)
                    subclass(Organization::class)
                    subclass(OrganizationAffiliation::class)
                    subclass(Parameters::class)
                    subclass(Patient::class)
                    subclass(PaymentNotice::class)
                    subclass(PaymentReconciliation::class)
                    subclass(Person::class)
                    subclass(PlanDefinition::class)
                    subclass(Practitioner::class)
                    subclass(PractitionerRole::class)
                    subclass(Procedure::class)
                    subclass(Provenance::class)
                    subclass(Questionnaire::class)
                    subclass(QuestionnaireResponse::class)
                    subclass(RelatedPerson::class)
                    subclass(RequestGroup::class)
                    subclass(ResearchDefinition::class)
                    subclass(ResearchElementDefinition::class)
                    subclass(ResearchStudy::class)
                    subclass(ResearchSubject::class)
                    subclass(Resource::class)
                    subclass(RiskAssessment::class)
                    subclass(RiskEvidenceSynthesis::class)
                    subclass(Schedule::class)
                    subclass(SearchParameter::class)
                    subclass(ServiceRequest::class)
                    subclass(Slot::class)
                    subclass(Specimen::class)
                    subclass(SpecimenDefinition::class)
                    subclass(StructureDefinition::class)
                    subclass(StructureMap::class)
                    subclass(Subscription::class)
                    subclass(Substance::class)
                    subclass(SubstanceNucleicAcid::class)
                    subclass(SubstancePolymer::class)
                    subclass(SubstanceProtein::class)
                    subclass(SubstanceReferenceInformation::class)
                    subclass(SubstanceSourceMaterial::class)
                    subclass(SubstanceSpecification::class)
                    subclass(SupplyDelivery::class)
                    subclass(SupplyRequest::class)
                    subclass(Task::class)
                    subclass(TerminologyCapabilities::class)
                    subclass(TestReport::class)
                    subclass(TestScript::class)
                    subclass(ValueSet::class)
                    subclass(VerificationResult::class)
                    subclass(VisionPrescription::class)
                }
            }
        }
    }

    object FhirElementFactory {

        fun <T : FhirR4> getFhirResourceType(klass: KClass<T>): String {
            return when (klass) {
                Account::class -> Account.resourceType()
                ActivityDefinition::class -> ActivityDefinition.resourceType()
                AdverseEvent::class -> AdverseEvent.resourceType()
                AllergyIntolerance::class -> AllergyIntolerance.resourceType()
                Appointment::class -> Appointment.resourceType()
                AppointmentResponse::class -> AppointmentResponse.resourceType()
                AuditEvent::class -> AuditEvent.resourceType()
                Basic::class -> Basic.resourceType()
                Binary::class -> Binary.resourceType()
                BiologicallyDerivedProduct::class -> BiologicallyDerivedProduct.resourceType()
                BodyStructure::class -> BodyStructure.resourceType()
                Bundle::class -> Bundle.resourceType()
                CapabilityStatement::class -> CapabilityStatement.resourceType()
                CarePlan::class -> CarePlan.resourceType()
                CareTeam::class -> CareTeam.resourceType()
                CatalogEntry::class -> CatalogEntry.resourceType()
                ChargeItem::class -> ChargeItem.resourceType()
                ChargeItemDefinition::class -> ChargeItemDefinition.resourceType()
                Claim::class -> Claim.resourceType()
                ClaimResponse::class -> ClaimResponse.resourceType()
                ClinicalImpression::class -> ClinicalImpression.resourceType()
                CodeSystem::class -> CodeSystem.resourceType()
                Communication::class -> Communication.resourceType()
                CommunicationRequest::class -> CommunicationRequest.resourceType()
                CompartmentDefinition::class -> CompartmentDefinition.resourceType()
                Composition::class -> Composition.resourceType()
                ConceptMap::class -> ConceptMap.resourceType()
                Condition::class -> Condition.resourceType()
                Consent::class -> Consent.resourceType()
                Contract::class -> Contract.resourceType()
                Coverage::class -> Coverage.resourceType()
                CoverageEligibilityRequest::class -> CoverageEligibilityRequest.resourceType()
                CoverageEligibilityResponse::class -> CoverageEligibilityResponse.resourceType()
                DetectedIssue::class -> DetectedIssue.resourceType()
                Device::class -> Device.resourceType()
                DeviceDefinition::class -> DeviceDefinition.resourceType()
                DeviceMetric::class -> DeviceMetric.resourceType()
                DeviceRequest::class -> DeviceRequest.resourceType()
                DeviceUseStatement::class -> DeviceUseStatement.resourceType()
                DiagnosticReport::class -> DiagnosticReport.resourceType()
                DocumentManifest::class -> DocumentManifest.resourceType()
                DocumentReference::class -> DocumentReference.resourceType()
                DomainResource::class -> DomainResource.resourceType()
                EffectEvidenceSynthesis::class -> EffectEvidenceSynthesis.resourceType()
                Encounter::class -> Encounter.resourceType()
                Endpoint::class -> Endpoint.resourceType()
                EnrollmentRequest::class -> EnrollmentRequest.resourceType()
                EnrollmentResponse::class -> EnrollmentResponse.resourceType()
                EpisodeOfCare::class -> EpisodeOfCare.resourceType()
                EventDefinition::class -> EventDefinition.resourceType()
                Evidence::class -> Evidence.resourceType()
                EvidenceVariable::class -> EvidenceVariable.resourceType()
                ExplanationOfBenefit::class -> ExplanationOfBenefit.resourceType()
                FamilyMemberHistory::class -> FamilyMemberHistory.resourceType()
                Flag::class -> Flag.resourceType()
                Goal::class -> Goal.resourceType()
                GraphDefinition::class -> GraphDefinition.resourceType()
                Group::class -> Group.resourceType()
                GuidanceResponse::class -> GuidanceResponse.resourceType()
                HealthcareService::class -> HealthcareService.resourceType()
                ImagingStudy::class -> ImagingStudy.resourceType()
                Immunization::class -> Immunization.resourceType()
                ImmunizationEvaluation::class -> ImmunizationEvaluation.resourceType()
                ImmunizationRecommendation::class -> ImmunizationRecommendation.resourceType()
                ImplementationGuide::class -> ImplementationGuide.resourceType()
                InsurancePlan::class -> InsurancePlan.resourceType()
                Invoice::class -> Invoice.resourceType()
                Library::class -> Library.resourceType()
                Linkage::class -> Linkage.resourceType()
                List::class -> List.resourceType()
                Location::class -> Location.resourceType()
                Measure::class -> Measure.resourceType()
                MeasureReport::class -> MeasureReport.resourceType()
                Media::class -> Media.resourceType()
                Medication::class -> Medication.resourceType()
                MedicationAdministration::class -> MedicationAdministration.resourceType()
                MedicationDispense::class -> MedicationDispense.resourceType()
                MedicationKnowledge::class -> MedicationKnowledge.resourceType()
                MedicationRequest::class -> MedicationRequest.resourceType()
                MedicationStatement::class -> MedicationStatement.resourceType()
                MedicinalProduct::class -> MedicinalProduct.resourceType()
                MedicinalProductAuthorization::class -> MedicinalProductAuthorization.resourceType()
                MedicinalProductContraindication::class -> MedicinalProductContraindication.resourceType()
                MedicinalProductIndication::class -> MedicinalProductIndication.resourceType()
                MedicinalProductIngredient::class -> MedicinalProductIngredient.resourceType()
                MedicinalProductInteraction::class -> MedicinalProductInteraction.resourceType()
                MedicinalProductManufactured::class -> MedicinalProductManufactured.resourceType()
                MedicinalProductPackaged::class -> MedicinalProductPackaged.resourceType()
                MedicinalProductPharmaceutical::class -> MedicinalProductPharmaceutical.resourceType()
                MedicinalProductUndesirableEffect::class -> MedicinalProductUndesirableEffect.resourceType()
                MessageDefinition::class -> MessageDefinition.resourceType()
                MessageHeader::class -> MessageHeader.resourceType()
                MolecularSequence::class -> MolecularSequence.resourceType()
                NamingSystem::class -> NamingSystem.resourceType()
                NutritionOrder::class -> NutritionOrder.resourceType()
                Observation::class -> Observation.resourceType()
                ObservationDefinition::class -> ObservationDefinition.resourceType()
                OperationDefinition::class -> OperationDefinition.resourceType()
                OperationOutcome::class -> OperationOutcome.resourceType()
                Organization::class -> Organization.resourceType()
                OrganizationAffiliation::class -> OrganizationAffiliation.resourceType()
                Parameters::class -> Parameters.resourceType()
                Patient::class -> Patient.resourceType()
                PaymentNotice::class -> PaymentNotice.resourceType()
                PaymentReconciliation::class -> PaymentReconciliation.resourceType()
                Person::class -> Person.resourceType()
                PlanDefinition::class -> PlanDefinition.resourceType()
                Practitioner::class -> Practitioner.resourceType()
                PractitionerRole::class -> PractitionerRole.resourceType()
                Procedure::class -> Procedure.resourceType()
                Provenance::class -> Provenance.resourceType()
                Questionnaire::class -> Questionnaire.resourceType()
                QuestionnaireResponse::class -> QuestionnaireResponse.resourceType()
                RelatedPerson::class -> RelatedPerson.resourceType()
                RequestGroup::class -> RequestGroup.resourceType()
                ResearchDefinition::class -> ResearchDefinition.resourceType()
                ResearchElementDefinition::class -> ResearchElementDefinition.resourceType()
                ResearchStudy::class -> ResearchStudy.resourceType()
                ResearchSubject::class -> ResearchSubject.resourceType()
                Resource::class -> Resource.resourceType()
                RiskAssessment::class -> RiskAssessment.resourceType()
                RiskEvidenceSynthesis::class -> RiskEvidenceSynthesis.resourceType()
                Schedule::class -> Schedule.resourceType()
                SearchParameter::class -> SearchParameter.resourceType()
                ServiceRequest::class -> ServiceRequest.resourceType()
                Slot::class -> Slot.resourceType()
                Specimen::class -> Specimen.resourceType()
                SpecimenDefinition::class -> SpecimenDefinition.resourceType()
                StructureDefinition::class -> StructureDefinition.resourceType()
                StructureMap::class -> StructureMap.resourceType()
                Subscription::class -> Subscription.resourceType()
                Substance::class -> Substance.resourceType()
                SubstanceNucleicAcid::class -> SubstanceNucleicAcid.resourceType()
                SubstancePolymer::class -> SubstancePolymer.resourceType()
                SubstanceProtein::class -> SubstanceProtein.resourceType()
                SubstanceReferenceInformation::class -> SubstanceReferenceInformation.resourceType()
                SubstanceSourceMaterial::class -> SubstanceSourceMaterial.resourceType()
                SubstanceSpecification::class -> SubstanceSpecification.resourceType()
                SupplyDelivery::class -> SupplyDelivery.resourceType()
                SupplyRequest::class -> SupplyRequest.resourceType()
                Task::class -> Task.resourceType()
                TerminologyCapabilities::class -> TerminologyCapabilities.resourceType()
                TestReport::class -> TestReport.resourceType()
                TestScript::class -> TestScript.resourceType()
                ValueSet::class -> ValueSet.resourceType()
                VerificationResult::class -> VerificationResult.resourceType()
                VisionPrescription::class -> VisionPrescription.resourceType()
                else -> throw IllegalArgumentException("FHIR class unknown: $klass")
            }
        }

        fun getFhirClass(resourceType: String): KClass<*> {
            return when (resourceType) {
                "Account" -> Account::class
                "ActivityDefinition" -> ActivityDefinition::class
                "AdverseEvent" -> AdverseEvent::class
                "AllergyIntolerance" -> AllergyIntolerance::class
                "Appointment" -> Appointment::class
                "AppointmentResponse" -> AppointmentResponse::class
                "AuditEvent" -> AuditEvent::class
                "Basic" -> Basic::class
                "Binary" -> Binary::class
                "BiologicallyDerivedProduct" -> BiologicallyDerivedProduct::class
                "BodyStructure" -> BodyStructure::class
                "Bundle" -> Bundle::class
                "CapabilityStatement" -> CapabilityStatement::class
                "CarePlan" -> CarePlan::class
                "CareTeam" -> CareTeam::class
                "CatalogEntry" -> CatalogEntry::class
                "ChargeItem" -> ChargeItem::class
                "ChargeItemDefinition" -> ChargeItemDefinition::class
                "Claim" -> Claim::class
                "ClaimResponse" -> ClaimResponse::class
                "ClinicalImpression" -> ClinicalImpression::class
                "CodeSystem" -> CodeSystem::class
                "Communication" -> Communication::class
                "CommunicationRequest" -> CommunicationRequest::class
                "CompartmentDefinition" -> CompartmentDefinition::class
                "Composition" -> Composition::class
                "ConceptMap" -> ConceptMap::class
                "Condition" -> Condition::class
                "Consent" -> Consent::class
                "Contract" -> Contract::class
                "Coverage" -> Coverage::class
                "CoverageEligibilityRequest" -> CoverageEligibilityRequest::class
                "CoverageEligibilityResponse" -> CoverageEligibilityResponse::class
                "DetectedIssue" -> DetectedIssue::class
                "Device" -> Device::class
                "DeviceDefinition" -> DeviceDefinition::class
                "DeviceMetric" -> DeviceMetric::class
                "DeviceRequest" -> DeviceRequest::class
                "DeviceUseStatement" -> DeviceUseStatement::class
                "DiagnosticReport" -> DiagnosticReport::class
                "DocumentManifest" -> DocumentManifest::class
                "DocumentReference" -> DocumentReference::class
                "DomainResource" -> DomainResource::class
                "EffectEvidenceSynthesis" -> EffectEvidenceSynthesis::class
                "Encounter" -> Encounter::class
                "Endpoint" -> Endpoint::class
                "EnrollmentRequest" -> EnrollmentRequest::class
                "EnrollmentResponse" -> EnrollmentResponse::class
                "EpisodeOfCare" -> EpisodeOfCare::class
                "EventDefinition" -> EventDefinition::class
                "Evidence" -> Evidence::class
                "EvidenceVariable" -> EvidenceVariable::class
                "ExplanationOfBenefit" -> ExplanationOfBenefit::class
                "FamilyMemberHistory" -> FamilyMemberHistory::class
                "Flag" -> Flag::class
                "Goal" -> Goal::class
                "GraphDefinition" -> GraphDefinition::class
                "Group" -> Group::class
                "GuidanceResponse" -> GuidanceResponse::class
                "HealthcareService" -> HealthcareService::class
                "ImagingStudy" -> ImagingStudy::class
                "Immunization" -> Immunization::class
                "ImmunizationEvaluation" -> ImmunizationEvaluation::class
                "ImmunizationRecommendation" -> ImmunizationRecommendation::class
                "ImplementationGuide" -> ImplementationGuide::class
                "InsurancePlan" -> InsurancePlan::class
                "Invoice" -> Invoice::class
                "Library" -> Library::class
                "Linkage" -> Linkage::class
                "List" -> List::class
                "Location" -> Location::class
                "Measure" -> Measure::class
                "MeasureReport" -> MeasureReport::class
                "Media" -> Media::class
                "Medication" -> Medication::class
                "MedicationAdministration" -> MedicationAdministration::class
                "MedicationDispense" -> MedicationDispense::class
                "MedicationKnowledge" -> MedicationKnowledge::class
                "MedicationRequest" -> MedicationRequest::class
                "MedicationStatement" -> MedicationStatement::class
                "MedicinalProduct" -> MedicinalProduct::class
                "MedicinalProductAuthorization" -> MedicinalProductAuthorization::class
                "MedicinalProductContraindication" -> MedicinalProductContraindication::class
                "MedicinalProductIndication" -> MedicinalProductIndication::class
                "MedicinalProductIngredient" -> MedicinalProductIngredient::class
                "MedicinalProductInteraction" -> MedicinalProductInteraction::class
                "MedicinalProductManufactured" -> MedicinalProductManufactured::class
                "MedicinalProductPackaged" -> MedicinalProductPackaged::class
                "MedicinalProductPharmaceutical" -> MedicinalProductPharmaceutical::class
                "MedicinalProductUndesirableEffect" -> MedicinalProductUndesirableEffect::class
                "MessageDefinition" -> MessageDefinition::class
                "MessageHeader" -> MessageHeader::class
                "MolecularSequence" -> MolecularSequence::class
                "NamingSystem" -> NamingSystem::class
                "NutritionOrder" -> NutritionOrder::class
                "Observation" -> Observation::class
                "ObservationDefinition" -> ObservationDefinition::class
                "OperationDefinition" -> OperationDefinition::class
                "OperationOutcome" -> OperationOutcome::class
                "Organization" -> Organization::class
                "OrganizationAffiliation" -> OrganizationAffiliation::class
                "Parameters" -> Parameters::class
                "Patient" -> Patient::class
                "PaymentNotice" -> PaymentNotice::class
                "PaymentReconciliation" -> PaymentReconciliation::class
                "Person" -> Person::class
                "PlanDefinition" -> PlanDefinition::class
                "Practitioner" -> Practitioner::class
                "PractitionerRole" -> PractitionerRole::class
                "Procedure" -> Procedure::class
                "Provenance" -> Provenance::class
                "Questionnaire" -> Questionnaire::class
                "QuestionnaireResponse" -> QuestionnaireResponse::class
                "RelatedPerson" -> RelatedPerson::class
                "RequestGroup" -> RequestGroup::class
                "ResearchDefinition" -> ResearchDefinition::class
                "ResearchElementDefinition" -> ResearchElementDefinition::class
                "ResearchStudy" -> ResearchStudy::class
                "ResearchSubject" -> ResearchSubject::class
                "Resource" -> Resource::class
                "RiskAssessment" -> RiskAssessment::class
                "RiskEvidenceSynthesis" -> RiskEvidenceSynthesis::class
                "Schedule" -> Schedule::class
                "SearchParameter" -> SearchParameter::class
                "ServiceRequest" -> ServiceRequest::class
                "Slot" -> Slot::class
                "Specimen" -> Specimen::class
                "SpecimenDefinition" -> SpecimenDefinition::class
                "StructureDefinition" -> StructureDefinition::class
                "StructureMap" -> StructureMap::class
                "Subscription" -> Subscription::class
                "Substance" -> Substance::class
                "SubstanceNucleicAcid" -> SubstanceNucleicAcid::class
                "SubstancePolymer" -> SubstancePolymer::class
                "SubstanceProtein" -> SubstanceProtein::class
                "SubstanceReferenceInformation" -> SubstanceReferenceInformation::class
                "SubstanceSourceMaterial" -> SubstanceSourceMaterial::class
                "SubstanceSpecification" -> SubstanceSpecification::class
                "SupplyDelivery" -> SupplyDelivery::class
                "SupplyRequest" -> SupplyRequest::class
                "Task" -> Task::class
                "TerminologyCapabilities" -> TerminologyCapabilities::class
                "TestReport" -> TestReport::class
                "TestScript" -> TestScript::class
                "ValueSet" -> ValueSet::class
                "VerificationResult" -> VerificationResult::class
                "VisionPrescription" -> VisionPrescription::class
                else -> throw IllegalArgumentException("FHIR resourceType unknown: $resourceType")
            }
        }
    }
}
