/*
 * Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.hl7.fhir.stu3.model

import kotlin.reflect.KClass
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

object FhirHelper {

    object FhirSerializationModule {
        fun module(): SerializersModule {
            return SerializersModule {
                polymorphic(FhirStu3::class) {
                    subclass(Account::class)
                    subclass(AccountCoverage::class)
                    subclass(AccountGuarantor::class)
                    subclass(ActivityDefinition::class)
                    subclass(ActivityDefinitionDynamicValue::class)
                    subclass(ActivityDefinitionParticipant::class)
                    subclass(Address::class)
                    subclass(AdverseEvent::class)
                    subclass(AdverseEventSuspectEntity::class)
                    subclass(Age::class)
                    subclass(AllergyIntolerance::class)
                    subclass(AllergyIntoleranceReaction::class)
                    subclass(Annotation::class)
                    subclass(Appointment::class)
                    subclass(AppointmentParticipant::class)
                    subclass(AppointmentResponse::class)
                    subclass(Attachment::class)
                    subclass(AuditEvent::class)
                    subclass(AuditEventAgent::class)
                    subclass(AuditEventAgentNetwork::class)
                    subclass(AuditEventEntity::class)
                    subclass(AuditEventEntityDetail::class)
                    subclass(AuditEventSource::class)
                    subclass(BackboneElement::class)
                    subclass(Basic::class)
                    subclass(Binary::class)
                    subclass(BodySite::class)
                    subclass(Bundle::class)
                    subclass(BundleEntry::class)
                    subclass(BundleEntryRequest::class)
                    subclass(BundleEntryResponse::class)
                    subclass(BundleEntrySearch::class)
                    subclass(BundleLink::class)
                    subclass(CapabilityStatement::class)
                    subclass(CapabilityStatementDocument::class)
                    subclass(CapabilityStatementImplementation::class)
                    subclass(CapabilityStatementMessaging::class)
                    subclass(CapabilityStatementMessagingEndpoint::class)
                    subclass(CapabilityStatementMessagingEvent::class)
                    subclass(CapabilityStatementMessagingSupportedMessage::class)
                    subclass(CapabilityStatementRest::class)
                    subclass(CapabilityStatementRestInteraction::class)
                    subclass(CapabilityStatementRestOperation::class)
                    subclass(CapabilityStatementRestResource::class)
                    subclass(CapabilityStatementRestResourceInteraction::class)
                    subclass(CapabilityStatementRestResourceSearchParam::class)
                    subclass(CapabilityStatementRestSecurity::class)
                    subclass(CapabilityStatementRestSecurityCertificate::class)
                    subclass(CapabilityStatementSoftware::class)
                    subclass(CarePlan::class)
                    subclass(CarePlanActivity::class)
                    subclass(CarePlanActivityDetail::class)
                    subclass(CareTeam::class)
                    subclass(CareTeamParticipant::class)
                    subclass(ChargeItem::class)
                    subclass(ChargeItemParticipant::class)
                    subclass(ClaimResponse::class)
                    subclass(ClaimResponseAddItem::class)
                    subclass(ClaimResponseAddItemDetail::class)
                    subclass(ClaimResponseError::class)
                    subclass(ClaimResponseInsurance::class)
                    subclass(ClaimResponseItem::class)
                    subclass(ClaimResponseItemAdjudication::class)
                    subclass(ClaimResponseItemDetail::class)
                    subclass(ClaimResponseItemDetailSubDetail::class)
                    subclass(ClaimResponsePayment::class)
                    subclass(ClaimResponseProcessNote::class)
                    subclass(ClinicalImpression::class)
                    subclass(ClinicalImpressionFinding::class)
                    subclass(ClinicalImpressionInvestigation::class)
                    subclass(CodeSystem::class)
                    subclass(CodeSystemConcept::class)
                    subclass(CodeSystemConceptDesignation::class)
                    subclass(CodeSystemConceptProperty::class)
                    subclass(CodeSystemFilter::class)
                    subclass(CodeSystemProperty::class)
                    subclass(CodeableConcept::class)
                    subclass(Coding::class)
                    subclass(Communication::class)
                    subclass(CommunicationPayload::class)
                    subclass(CommunicationRequest::class)
                    subclass(CommunicationRequestPayload::class)
                    subclass(CommunicationRequestRequester::class)
                    subclass(CompartmentDefinition::class)
                    subclass(CompartmentDefinitionResource::class)
                    subclass(Composition::class)
                    subclass(CompositionAttester::class)
                    subclass(CompositionEvent::class)
                    subclass(CompositionRelatesTo::class)
                    subclass(CompositionSection::class)
                    subclass(ConceptMap::class)
                    subclass(ConceptMapGroup::class)
                    subclass(ConceptMapGroupElement::class)
                    subclass(ConceptMapGroupElementTarget::class)
                    subclass(ConceptMapGroupElementTargetDependsOn::class)
                    subclass(ConceptMapGroupUnmapped::class)
                    subclass(Condition::class)
                    subclass(ConditionEvidence::class)
                    subclass(ConditionStage::class)
                    subclass(Consent::class)
                    subclass(ConsentActor::class)
                    subclass(ConsentData::class)
                    subclass(ConsentExcept::class)
                    subclass(ConsentExceptActor::class)
                    subclass(ConsentExceptData::class)
                    subclass(ConsentPolicy::class)
                    subclass(ContactDetail::class)
                    subclass(ContactPoint::class)
                    subclass(Contract::class)
                    subclass(ContractAgent::class)
                    subclass(ContractFriendly::class)
                    subclass(ContractLegal::class)
                    subclass(ContractRule::class)
                    subclass(ContractSigner::class)
                    subclass(ContractTerm::class)
                    subclass(ContractTermAgent::class)
                    subclass(ContractTermValuedItem::class)
                    subclass(ContractValuedItem::class)
                    subclass(Contributor::class)
                    subclass(Count::class)
                    subclass(Coverage::class)
                    subclass(CoverageGrouping::class)
                    subclass(DataElement::class)
                    subclass(DataElementMapping::class)
                    subclass(DataRequirement::class)
                    subclass(DataRequirementCodeFilter::class)
                    subclass(DataRequirementDateFilter::class)
                    subclass(DetectedIssue::class)
                    subclass(DetectedIssueMitigation::class)
                    subclass(Device::class)
                    subclass(DeviceComponent::class)
                    subclass(DeviceComponentProductionSpecification::class)
                    subclass(DeviceMetric::class)
                    subclass(DeviceMetricCalibration::class)
                    subclass(DeviceRequest::class)
                    subclass(DeviceRequestRequester::class)
                    subclass(DeviceUdi::class)
                    subclass(DeviceUseStatement::class)
                    subclass(DiagnosticReport::class)
                    subclass(DiagnosticReportImage::class)
                    subclass(DiagnosticReportPerformer::class)
                    subclass(Distance::class)
                    subclass(DocumentManifest::class)
                    subclass(DocumentManifestContent::class)
                    subclass(DocumentManifestRelated::class)
                    subclass(DocumentReference::class)
                    subclass(DocumentReferenceContent::class)
                    subclass(DocumentReferenceContext::class)
                    subclass(DocumentReferenceContextRelated::class)
                    subclass(DocumentReferenceRelatesTo::class)
                    subclass(DomainResource::class)
                    subclass(Dosage::class)
                    subclass(Duration::class)
                    subclass(Element::class)
                    subclass(ElementDefinition::class)
                    subclass(ElementDefinitionBase::class)
                    subclass(ElementDefinitionBinding::class)
                    subclass(ElementDefinitionConstraint::class)
                    subclass(ElementDefinitionExample::class)
                    subclass(ElementDefinitionMapping::class)
                    subclass(ElementDefinitionSlicing::class)
                    subclass(ElementDefinitionSlicingDiscriminator::class)
                    subclass(ElementDefinitionType::class)
                    subclass(EligibilityRequest::class)
                    subclass(EligibilityResponse::class)
                    subclass(EligibilityResponseError::class)
                    subclass(EligibilityResponseInsurance::class)
                    subclass(EligibilityResponseInsuranceBenefitBalance::class)
                    subclass(EligibilityResponseInsuranceBenefitBalanceFinancial::class)
                    subclass(Encounter::class)
                    subclass(EncounterClassHistory::class)
                    subclass(EncounterDiagnosis::class)
                    subclass(EncounterHospitalization::class)
                    subclass(EncounterLocation::class)
                    subclass(EncounterParticipant::class)
                    subclass(EncounterStatusHistory::class)
                    subclass(Endpoint::class)
                    subclass(EnrollmentRequest::class)
                    subclass(EnrollmentResponse::class)
                    subclass(EpisodeOfCare::class)
                    subclass(EpisodeOfCareDiagnosis::class)
                    subclass(EpisodeOfCareStatusHistory::class)
                    subclass(ExpansionProfile::class)
                    subclass(ExpansionProfileDesignation::class)
                    subclass(ExpansionProfileDesignationExclude::class)
                    subclass(ExpansionProfileDesignationExcludeDesignation::class)
                    subclass(ExpansionProfileDesignationInclude::class)
                    subclass(ExpansionProfileDesignationIncludeDesignation::class)
                    subclass(ExpansionProfileExcludedSystem::class)
                    subclass(ExpansionProfileFixedVersion::class)
                    subclass(Extension::class)
                    subclass(FamilyMemberHistory::class)
                    subclass(FamilyMemberHistoryCondition::class)
                    subclass(Flag::class)
                    subclass(Goal::class)
                    subclass(GoalTarget::class)
                    subclass(GraphDefinition::class)
                    subclass(GraphDefinitionLink::class)
                    subclass(GraphDefinitionLinkTarget::class)
                    subclass(GraphDefinitionLinkTargetCompartment::class)
                    subclass(Group::class)
                    subclass(GroupCharacteristic::class)
                    subclass(GroupMember::class)
                    subclass(GuidanceResponse::class)
                    subclass(HealthcareService::class)
                    subclass(HealthcareServiceAvailableTime::class)
                    subclass(HealthcareServiceNotAvailable::class)
                    subclass(HumanName::class)
                    subclass(Identifier::class)
                    subclass(ImagingManifest::class)
                    subclass(ImagingManifestStudy::class)
                    subclass(ImagingManifestStudySeries::class)
                    subclass(ImagingManifestStudySeriesInstance::class)
                    subclass(ImagingStudy::class)
                    subclass(ImagingStudySeries::class)
                    subclass(ImagingStudySeriesInstance::class)
                    subclass(Immunization::class)
                    subclass(ImmunizationExplanation::class)
                    subclass(ImmunizationPractitioner::class)
                    subclass(ImmunizationReaction::class)
                    subclass(ImmunizationRecommendation::class)
                    subclass(ImmunizationRecommendationRecommendation::class)
                    subclass(ImmunizationRecommendationRecommendationDateCriterion::class)
                    subclass(ImmunizationRecommendationRecommendationProtocol::class)
                    subclass(ImmunizationVaccinationProtocol::class)
                    subclass(ImplementationGuide::class)
                    subclass(ImplementationGuideDependency::class)
                    subclass(ImplementationGuideGlobal::class)
                    subclass(ImplementationGuidePackage::class)
                    subclass(ImplementationGuidePackageResource::class)
                    subclass(ImplementationGuidePage::class)
                    subclass(Library::class)
                    subclass(Linkage::class)
                    subclass(LinkageItem::class)
                    subclass(List::class)
                    subclass(ListEntry::class)
                    subclass(Location::class)
                    subclass(LocationPosition::class)
                    subclass(Measure::class)
                    subclass(MeasureGroup::class)
                    subclass(MeasureGroupPopulation::class)
                    subclass(MeasureGroupStratifier::class)
                    subclass(MeasureReport::class)
                    subclass(MeasureReportGroup::class)
                    subclass(MeasureReportGroupPopulation::class)
                    subclass(MeasureReportGroupStratifier::class)
                    subclass(MeasureReportGroupStratifierStratum::class)
                    subclass(MeasureReportGroupStratifierStratumPopulation::class)
                    subclass(MeasureSupplementalData::class)
                    subclass(Media::class)
                    subclass(Medication::class)
                    subclass(MedicationAdministration::class)
                    subclass(MedicationAdministrationDosage::class)
                    subclass(MedicationAdministrationPerformer::class)
                    subclass(MedicationDispense::class)
                    subclass(MedicationDispensePerformer::class)
                    subclass(MedicationDispenseSubstitution::class)
                    subclass(MedicationIngredient::class)
                    subclass(MedicationPackage::class)
                    subclass(MedicationPackageBatch::class)
                    subclass(MedicationPackageContent::class)
                    subclass(MedicationRequest::class)
                    subclass(MedicationRequestDispenseRequest::class)
                    subclass(MedicationRequestRequester::class)
                    subclass(MedicationRequestSubstitution::class)
                    subclass(MedicationStatement::class)
                    subclass(MessageDefinition::class)
                    subclass(MessageDefinitionAllowedResponse::class)
                    subclass(MessageDefinitionFocus::class)
                    subclass(MessageHeader::class)
                    subclass(MessageHeaderDestination::class)
                    subclass(MessageHeaderResponse::class)
                    subclass(MessageHeaderSource::class)
                    subclass(Meta::class)
                    subclass(MetadataResource::class)
                    subclass(Money::class)
                    subclass(NamingSystem::class)
                    subclass(NamingSystemUniqueId::class)
                    subclass(Narrative::class)
                    subclass(NutritionOrder::class)
                    subclass(NutritionOrderEnteralFormula::class)
                    subclass(NutritionOrderEnteralFormulaAdministration::class)
                    subclass(NutritionOrderOralDiet::class)
                    subclass(NutritionOrderOralDietNutrient::class)
                    subclass(NutritionOrderOralDietTexture::class)
                    subclass(NutritionOrderSupplement::class)
                    subclass(Observation::class)
                    subclass(ObservationComponent::class)
                    subclass(ObservationReferenceRange::class)
                    subclass(ObservationRelated::class)
                    subclass(OperationDefinition::class)
                    subclass(OperationDefinitionOverload::class)
                    subclass(OperationDefinitionParameter::class)
                    subclass(OperationDefinitionParameterBinding::class)
                    subclass(OperationOutcome::class)
                    subclass(OperationOutcomeIssue::class)
                    subclass(Organization::class)
                    subclass(OrganizationContact::class)
                    subclass(ParameterDefinition::class)
                    subclass(Parameters::class)
                    subclass(ParametersParameter::class)
                    subclass(Patient::class)
                    subclass(PatientAnimal::class)
                    subclass(PatientCommunication::class)
                    subclass(PatientContact::class)
                    subclass(PatientLink::class)
                    subclass(PaymentNotice::class)
                    subclass(PaymentReconciliation::class)
                    subclass(PaymentReconciliationDetail::class)
                    subclass(PaymentReconciliationProcessNote::class)
                    subclass(Period::class)
                    subclass(Person::class)
                    subclass(PersonLink::class)
                    subclass(PlanDefinition::class)
                    subclass(PlanDefinitionAction::class)
                    subclass(PlanDefinitionActionCondition::class)
                    subclass(PlanDefinitionActionDynamicValue::class)
                    subclass(PlanDefinitionActionParticipant::class)
                    subclass(PlanDefinitionActionRelatedAction::class)
                    subclass(PlanDefinitionGoal::class)
                    subclass(PlanDefinitionGoalTarget::class)
                    subclass(Practitioner::class)
                    subclass(PractitionerQualification::class)
                    subclass(PractitionerRole::class)
                    subclass(PractitionerRoleAvailableTime::class)
                    subclass(PractitionerRoleNotAvailable::class)
                    subclass(Procedure::class)
                    subclass(ProcedureFocalDevice::class)
                    subclass(ProcedurePerformer::class)
                    subclass(ProcedureRequest::class)
                    subclass(ProcedureRequestRequester::class)
                    subclass(ProcessRequest::class)
                    subclass(ProcessRequestItem::class)
                    subclass(ProcessResponse::class)
                    subclass(ProcessResponseProcessNote::class)
                    subclass(Provenance::class)
                    subclass(ProvenanceAgent::class)
                    subclass(ProvenanceEntity::class)
                    subclass(Quantity::class)
                    subclass(Questionnaire::class)
                    subclass(QuestionnaireItem::class)
                    subclass(QuestionnaireItemEnableWhen::class)
                    subclass(QuestionnaireItemOption::class)
                    subclass(QuestionnaireResponse::class)
                    subclass(QuestionnaireResponseItem::class)
                    subclass(QuestionnaireResponseItemAnswer::class)
                    subclass(Range::class)
                    subclass(Ratio::class)
                    subclass(Reference::class)
                    subclass(ReferralRequest::class)
                    subclass(ReferralRequestRequester::class)
                    subclass(RelatedArtifact::class)
                    subclass(RelatedPerson::class)
                    subclass(RequestGroup::class)
                    subclass(RequestGroupAction::class)
                    subclass(RequestGroupActionCondition::class)
                    subclass(RequestGroupActionRelatedAction::class)
                    subclass(ResearchStudy::class)
                    subclass(ResearchStudyArm::class)
                    subclass(ResearchSubject::class)
                    subclass(Resource::class)
                    subclass(RiskAssessment::class)
                    subclass(RiskAssessmentPrediction::class)
                    subclass(SampledData::class)
                    subclass(Schedule::class)
                    subclass(SearchParameter::class)
                    subclass(SearchParameterComponent::class)
                    subclass(Sequence::class)
                    subclass(SequenceQuality::class)
                    subclass(SequenceReferenceSeq::class)
                    subclass(SequenceRepository::class)
                    subclass(SequenceVariant::class)
                    subclass(ServiceDefinition::class)
                    subclass(Signature::class)
                    subclass(Slot::class)
                    subclass(Specimen::class)
                    subclass(SpecimenCollection::class)
                    subclass(SpecimenContainer::class)
                    subclass(SpecimenProcessing::class)
                    subclass(StructureDefinition::class)
                    subclass(StructureDefinitionDifferential::class)
                    subclass(StructureDefinitionMapping::class)
                    subclass(StructureDefinitionSnapshot::class)
                    subclass(StructureMap::class)
                    subclass(StructureMapGroup::class)
                    subclass(StructureMapGroupInput::class)
                    subclass(StructureMapGroupRule::class)
                    subclass(StructureMapGroupRuleDependent::class)
                    subclass(StructureMapGroupRuleSource::class)
                    subclass(StructureMapGroupRuleTarget::class)
                    subclass(StructureMapGroupRuleTargetParameter::class)
                    subclass(StructureMapStructure::class)
                    subclass(Subscription::class)
                    subclass(SubscriptionChannel::class)
                    subclass(Substance::class)
                    subclass(SubstanceIngredient::class)
                    subclass(SubstanceInstance::class)
                    subclass(SupplyDelivery::class)
                    subclass(SupplyDeliverySuppliedItem::class)
                    subclass(SupplyRequest::class)
                    subclass(SupplyRequestOrderedItem::class)
                    subclass(SupplyRequestRequester::class)
                    subclass(Task::class)
                    subclass(TaskInput::class)
                    subclass(TaskOutput::class)
                    subclass(TaskRequester::class)
                    subclass(TaskRestriction::class)
                    subclass(TestReport::class)
                    subclass(TestReportParticipant::class)
                    subclass(TestReportSetup::class)
                    subclass(TestReportSetupAction::class)
                    subclass(TestReportSetupActionAssert::class)
                    subclass(TestReportSetupActionOperation::class)
                    subclass(TestReportTeardown::class)
                    subclass(TestReportTeardownAction::class)
                    subclass(TestReportTest::class)
                    subclass(TestReportTestAction::class)
                    subclass(TestScript::class)
                    subclass(TestScriptDestination::class)
                    subclass(TestScriptFixture::class)
                    subclass(TestScriptMetadata::class)
                    subclass(TestScriptMetadataCapability::class)
                    subclass(TestScriptMetadataLink::class)
                    subclass(TestScriptOrigin::class)
                    subclass(TestScriptRule::class)
                    subclass(TestScriptRuleParam::class)
                    subclass(TestScriptRuleset::class)
                    subclass(TestScriptRulesetRule::class)
                    subclass(TestScriptRulesetRuleParam::class)
                    subclass(TestScriptSetup::class)
                    subclass(TestScriptSetupAction::class)
                    subclass(TestScriptSetupActionAssert::class)
                    subclass(TestScriptSetupActionAssertRule::class)
                    subclass(TestScriptSetupActionAssertRuleParam::class)
                    subclass(TestScriptSetupActionAssertRuleset::class)
                    subclass(TestScriptSetupActionAssertRulesetRule::class)
                    subclass(TestScriptSetupActionAssertRulesetRuleParam::class)
                    subclass(TestScriptSetupActionOperation::class)
                    subclass(TestScriptSetupActionOperationRequestHeader::class)
                    subclass(TestScriptTeardown::class)
                    subclass(TestScriptTeardownAction::class)
                    subclass(TestScriptTest::class)
                    subclass(TestScriptTestAction::class)
                    subclass(TestScriptVariable::class)
                    subclass(Timing::class)
                    subclass(TimingRepeat::class)
                    subclass(TriggerDefinition::class)
                    subclass(UsageContext::class)
                    subclass(ValueSet::class)
                    subclass(ValueSetCompose::class)
                    subclass(ValueSetComposeInclude::class)
                    subclass(ValueSetComposeIncludeConcept::class)
                    subclass(ValueSetComposeIncludeConceptDesignation::class)
                    subclass(ValueSetComposeIncludeFilter::class)
                    subclass(ValueSetExpansion::class)
                    subclass(ValueSetExpansionContains::class)
                    subclass(ValueSetExpansionParameter::class)
                    subclass(VisionPrescription::class)
                    subclass(VisionPrescriptionDispense::class)
                }
                polymorphic(FhirResource::class) {
                    subclass(Account::class)
                    subclass(ActivityDefinition::class)
                    subclass(AdverseEvent::class)
                    subclass(AllergyIntolerance::class)
                    subclass(Appointment::class)
                    subclass(AppointmentResponse::class)
                    subclass(AuditEvent::class)
                    subclass(Basic::class)
                    subclass(Binary::class)
                    subclass(BodySite::class)
                    subclass(Bundle::class)
                    subclass(CapabilityStatement::class)
                    subclass(CarePlan::class)
                    subclass(CareTeam::class)
                    subclass(ChargeItem::class)
                    subclass(ClaimResponse::class)
                    subclass(ClinicalImpression::class)
                    subclass(CodeSystem::class)
                    subclass(Communication::class)
                    subclass(CommunicationRequest::class)
                    subclass(CompartmentDefinition::class)
                    subclass(Composition::class)
                    subclass(ConceptMap::class)
                    subclass(Condition::class)
                    subclass(Consent::class)
                    subclass(Contract::class)
                    subclass(Coverage::class)
                    subclass(DataElement::class)
                    subclass(DetectedIssue::class)
                    subclass(Device::class)
                    subclass(DeviceComponent::class)
                    subclass(DeviceMetric::class)
                    subclass(DeviceRequest::class)
                    subclass(DeviceUseStatement::class)
                    subclass(DiagnosticReport::class)
                    subclass(DocumentManifest::class)
                    subclass(DocumentReference::class)
                    subclass(DomainResource::class)
                    subclass(EligibilityRequest::class)
                    subclass(EligibilityResponse::class)
                    subclass(Encounter::class)
                    subclass(Endpoint::class)
                    subclass(EnrollmentRequest::class)
                    subclass(EnrollmentResponse::class)
                    subclass(EpisodeOfCare::class)
                    subclass(ExpansionProfile::class)
                    subclass(FamilyMemberHistory::class)
                    subclass(Flag::class)
                    subclass(Goal::class)
                    subclass(GraphDefinition::class)
                    subclass(Group::class)
                    subclass(GuidanceResponse::class)
                    subclass(HealthcareService::class)
                    subclass(ImagingManifest::class)
                    subclass(ImagingStudy::class)
                    subclass(Immunization::class)
                    subclass(ImmunizationRecommendation::class)
                    subclass(ImplementationGuide::class)
                    subclass(Library::class)
                    subclass(Linkage::class)
                    subclass(List::class)
                    subclass(Location::class)
                    subclass(Measure::class)
                    subclass(MeasureReport::class)
                    subclass(Media::class)
                    subclass(Medication::class)
                    subclass(MedicationAdministration::class)
                    subclass(MedicationDispense::class)
                    subclass(MedicationRequest::class)
                    subclass(MedicationStatement::class)
                    subclass(MessageDefinition::class)
                    subclass(MessageHeader::class)
                    subclass(NamingSystem::class)
                    subclass(NutritionOrder::class)
                    subclass(Observation::class)
                    subclass(OperationDefinition::class)
                    subclass(OperationOutcome::class)
                    subclass(Organization::class)
                    subclass(Parameters::class)
                    subclass(Patient::class)
                    subclass(PaymentNotice::class)
                    subclass(PaymentReconciliation::class)
                    subclass(Person::class)
                    subclass(PlanDefinition::class)
                    subclass(Practitioner::class)
                    subclass(PractitionerRole::class)
                    subclass(Procedure::class)
                    subclass(ProcedureRequest::class)
                    subclass(ProcessRequest::class)
                    subclass(ProcessResponse::class)
                    subclass(Provenance::class)
                    subclass(Questionnaire::class)
                    subclass(QuestionnaireResponse::class)
                    subclass(ReferralRequest::class)
                    subclass(RelatedPerson::class)
                    subclass(RequestGroup::class)
                    subclass(ResearchStudy::class)
                    subclass(ResearchSubject::class)
                    subclass(Resource::class)
                    subclass(RiskAssessment::class)
                    subclass(Schedule::class)
                    subclass(SearchParameter::class)
                    subclass(Sequence::class)
                    subclass(ServiceDefinition::class)
                    subclass(Slot::class)
                    subclass(Specimen::class)
                    subclass(StructureDefinition::class)
                    subclass(StructureMap::class)
                    subclass(Subscription::class)
                    subclass(Substance::class)
                    subclass(SupplyDelivery::class)
                    subclass(SupplyRequest::class)
                    subclass(Task::class)
                    subclass(TestReport::class)
                    subclass(TestScript::class)
                    subclass(ValueSet::class)
                    subclass(VisionPrescription::class)
                }
            }
        }
    }

    object FhirElementFactory {

        fun <T : FhirStu3> getFhirResourceType(klass: KClass<T>): String? {
            return when (klass) {
                Account::class -> Account.resourceType()
                ActivityDefinition::class -> ActivityDefinition.resourceType()
                AdverseEvent::class -> AdverseEvent.resourceType()
                AllergyIntolerance::class -> AllergyIntolerance.resourceType()
                Appointment::class -> Appointment.resourceType()
                AppointmentResponse::class -> AppointmentResponse.resourceType()
                AuditEvent::class -> AuditEvent.resourceType()
                Basic::class -> Basic.resourceType()
                Binary::class -> Binary.resourceType()
                BodySite::class -> BodySite.resourceType()
                Bundle::class -> Bundle.resourceType()
                CapabilityStatement::class -> CapabilityStatement.resourceType()
                CarePlan::class -> CarePlan.resourceType()
                CareTeam::class -> CareTeam.resourceType()
                ChargeItem::class -> ChargeItem.resourceType()
                ClaimResponse::class -> ClaimResponse.resourceType()
                ClinicalImpression::class -> ClinicalImpression.resourceType()
                CodeSystem::class -> CodeSystem.resourceType()
                Communication::class -> Communication.resourceType()
                CommunicationRequest::class -> CommunicationRequest.resourceType()
                CompartmentDefinition::class -> CompartmentDefinition.resourceType()
                Composition::class -> Composition.resourceType()
                ConceptMap::class -> ConceptMap.resourceType()
                Condition::class -> Condition.resourceType()
                Consent::class -> Consent.resourceType()
                Contract::class -> Contract.resourceType()
                Coverage::class -> Coverage.resourceType()
                DataElement::class -> DataElement.resourceType()
                DetectedIssue::class -> DetectedIssue.resourceType()
                Device::class -> Device.resourceType()
                DeviceComponent::class -> DeviceComponent.resourceType()
                DeviceMetric::class -> DeviceMetric.resourceType()
                DeviceRequest::class -> DeviceRequest.resourceType()
                DeviceUseStatement::class -> DeviceUseStatement.resourceType()
                DiagnosticReport::class -> DiagnosticReport.resourceType()
                DocumentManifest::class -> DocumentManifest.resourceType()
                DocumentReference::class -> DocumentReference.resourceType()
                DomainResource::class -> DomainResource.resourceType()
                EligibilityRequest::class -> EligibilityRequest.resourceType()
                EligibilityResponse::class -> EligibilityResponse.resourceType()
                Encounter::class -> Encounter.resourceType()
                Endpoint::class -> Endpoint.resourceType()
                EnrollmentRequest::class -> EnrollmentRequest.resourceType()
                EnrollmentResponse::class -> EnrollmentResponse.resourceType()
                EpisodeOfCare::class -> EpisodeOfCare.resourceType()
                ExpansionProfile::class -> ExpansionProfile.resourceType()
                FamilyMemberHistory::class -> FamilyMemberHistory.resourceType()
                Flag::class -> Flag.resourceType()
                Goal::class -> Goal.resourceType()
                GraphDefinition::class -> GraphDefinition.resourceType()
                Group::class -> Group.resourceType()
                GuidanceResponse::class -> GuidanceResponse.resourceType()
                HealthcareService::class -> HealthcareService.resourceType()
                ImagingManifest::class -> ImagingManifest.resourceType()
                ImagingStudy::class -> ImagingStudy.resourceType()
                Immunization::class -> Immunization.resourceType()
                ImmunizationRecommendation::class -> ImmunizationRecommendation.resourceType()
                ImplementationGuide::class -> ImplementationGuide.resourceType()
                Library::class -> Library.resourceType()
                Linkage::class -> Linkage.resourceType()
                List::class -> List.resourceType()
                Location::class -> Location.resourceType()
                Measure::class -> Measure.resourceType()
                MeasureReport::class -> MeasureReport.resourceType()
                Media::class -> Media.resourceType()
                Medication::class -> Medication.resourceType()
                MedicationAdministration::class -> MedicationAdministration.resourceType()
                MedicationDispense::class -> MedicationDispense.resourceType()
                MedicationRequest::class -> MedicationRequest.resourceType()
                MedicationStatement::class -> MedicationStatement.resourceType()
                MessageDefinition::class -> MessageDefinition.resourceType()
                MessageHeader::class -> MessageHeader.resourceType()
                NamingSystem::class -> NamingSystem.resourceType()
                NutritionOrder::class -> NutritionOrder.resourceType()
                Observation::class -> Observation.resourceType()
                OperationDefinition::class -> OperationDefinition.resourceType()
                OperationOutcome::class -> OperationOutcome.resourceType()
                Organization::class -> Organization.resourceType()
                Parameters::class -> Parameters.resourceType()
                Patient::class -> Patient.resourceType()
                PaymentNotice::class -> PaymentNotice.resourceType()
                PaymentReconciliation::class -> PaymentReconciliation.resourceType()
                Person::class -> Person.resourceType()
                PlanDefinition::class -> PlanDefinition.resourceType()
                Practitioner::class -> Practitioner.resourceType()
                PractitionerRole::class -> PractitionerRole.resourceType()
                Procedure::class -> Procedure.resourceType()
                ProcedureRequest::class -> ProcedureRequest.resourceType()
                ProcessRequest::class -> ProcessRequest.resourceType()
                ProcessResponse::class -> ProcessResponse.resourceType()
                Provenance::class -> Provenance.resourceType()
                Questionnaire::class -> Questionnaire.resourceType()
                QuestionnaireResponse::class -> QuestionnaireResponse.resourceType()
                ReferralRequest::class -> ReferralRequest.resourceType()
                RelatedPerson::class -> RelatedPerson.resourceType()
                RequestGroup::class -> RequestGroup.resourceType()
                ResearchStudy::class -> ResearchStudy.resourceType()
                ResearchSubject::class -> ResearchSubject.resourceType()
                Resource::class -> Resource.resourceType()
                RiskAssessment::class -> RiskAssessment.resourceType()
                Schedule::class -> Schedule.resourceType()
                SearchParameter::class -> SearchParameter.resourceType()
                Sequence::class -> Sequence.resourceType()
                ServiceDefinition::class -> ServiceDefinition.resourceType()
                Slot::class -> Slot.resourceType()
                Specimen::class -> Specimen.resourceType()
                StructureDefinition::class -> StructureDefinition.resourceType()
                StructureMap::class -> StructureMap.resourceType()
                Subscription::class -> Subscription.resourceType()
                Substance::class -> Substance.resourceType()
                SupplyDelivery::class -> SupplyDelivery.resourceType()
                SupplyRequest::class -> SupplyRequest.resourceType()
                Task::class -> Task.resourceType()
                TestReport::class -> TestReport.resourceType()
                TestScript::class -> TestScript.resourceType()
                ValueSet::class -> ValueSet.resourceType()
                VisionPrescription::class -> VisionPrescription.resourceType()
                else -> null
            }
        }

        fun getFhirClass(resourceType: String): KClass<*>? {
            return when (resourceType.lowercase()) {
                "account" -> Account::class
                "activitydefinition" -> ActivityDefinition::class
                "adverseevent" -> AdverseEvent::class
                "allergyintolerance" -> AllergyIntolerance::class
                "appointment" -> Appointment::class
                "appointmentresponse" -> AppointmentResponse::class
                "auditevent" -> AuditEvent::class
                "basic" -> Basic::class
                "binary" -> Binary::class
                "bodysite" -> BodySite::class
                "bundle" -> Bundle::class
                "capabilitystatement" -> CapabilityStatement::class
                "careplan" -> CarePlan::class
                "careteam" -> CareTeam::class
                "chargeitem" -> ChargeItem::class
                "claimresponse" -> ClaimResponse::class
                "clinicalimpression" -> ClinicalImpression::class
                "codesystem" -> CodeSystem::class
                "communication" -> Communication::class
                "communicationrequest" -> CommunicationRequest::class
                "compartmentdefinition" -> CompartmentDefinition::class
                "composition" -> Composition::class
                "conceptmap" -> ConceptMap::class
                "condition" -> Condition::class
                "consent" -> Consent::class
                "contract" -> Contract::class
                "coverage" -> Coverage::class
                "dataelement" -> DataElement::class
                "detectedissue" -> DetectedIssue::class
                "device" -> Device::class
                "devicecomponent" -> DeviceComponent::class
                "devicemetric" -> DeviceMetric::class
                "devicerequest" -> DeviceRequest::class
                "deviceusestatement" -> DeviceUseStatement::class
                "diagnosticreport" -> DiagnosticReport::class
                "documentmanifest" -> DocumentManifest::class
                "documentreference" -> DocumentReference::class
                "domainresource" -> DomainResource::class
                "eligibilityrequest" -> EligibilityRequest::class
                "eligibilityresponse" -> EligibilityResponse::class
                "encounter" -> Encounter::class
                "endpoint" -> Endpoint::class
                "enrollmentrequest" -> EnrollmentRequest::class
                "enrollmentresponse" -> EnrollmentResponse::class
                "episodeofcare" -> EpisodeOfCare::class
                "expansionprofile" -> ExpansionProfile::class
                "familymemberhistory" -> FamilyMemberHistory::class
                "flag" -> Flag::class
                "goal" -> Goal::class
                "graphdefinition" -> GraphDefinition::class
                "group" -> Group::class
                "guidanceresponse" -> GuidanceResponse::class
                "healthcareservice" -> HealthcareService::class
                "imagingmanifest" -> ImagingManifest::class
                "imagingstudy" -> ImagingStudy::class
                "immunization" -> Immunization::class
                "immunizationrecommendation" -> ImmunizationRecommendation::class
                "implementationguide" -> ImplementationGuide::class
                "library" -> Library::class
                "linkage" -> Linkage::class
                "list" -> List::class
                "location" -> Location::class
                "measure" -> Measure::class
                "measurereport" -> MeasureReport::class
                "media" -> Media::class
                "medication" -> Medication::class
                "medicationadministration" -> MedicationAdministration::class
                "medicationdispense" -> MedicationDispense::class
                "medicationrequest" -> MedicationRequest::class
                "medicationstatement" -> MedicationStatement::class
                "messagedefinition" -> MessageDefinition::class
                "messageheader" -> MessageHeader::class
                "namingsystem" -> NamingSystem::class
                "nutritionorder" -> NutritionOrder::class
                "observation" -> Observation::class
                "operationdefinition" -> OperationDefinition::class
                "operationoutcome" -> OperationOutcome::class
                "organization" -> Organization::class
                "parameters" -> Parameters::class
                "patient" -> Patient::class
                "paymentnotice" -> PaymentNotice::class
                "paymentreconciliation" -> PaymentReconciliation::class
                "person" -> Person::class
                "plandefinition" -> PlanDefinition::class
                "practitioner" -> Practitioner::class
                "practitionerrole" -> PractitionerRole::class
                "procedure" -> Procedure::class
                "procedurerequest" -> ProcedureRequest::class
                "processrequest" -> ProcessRequest::class
                "processresponse" -> ProcessResponse::class
                "provenance" -> Provenance::class
                "questionnaire" -> Questionnaire::class
                "questionnaireresponse" -> QuestionnaireResponse::class
                "referralrequest" -> ReferralRequest::class
                "relatedperson" -> RelatedPerson::class
                "requestgroup" -> RequestGroup::class
                "researchstudy" -> ResearchStudy::class
                "researchsubject" -> ResearchSubject::class
                "resource" -> Resource::class
                "riskassessment" -> RiskAssessment::class
                "schedule" -> Schedule::class
                "searchparameter" -> SearchParameter::class
                "sequence" -> Sequence::class
                "servicedefinition" -> ServiceDefinition::class
                "slot" -> Slot::class
                "specimen" -> Specimen::class
                "structuredefinition" -> StructureDefinition::class
                "structuremap" -> StructureMap::class
                "subscription" -> Subscription::class
                "substance" -> Substance::class
                "supplydelivery" -> SupplyDelivery::class
                "supplyrequest" -> SupplyRequest::class
                "task" -> Task::class
                "testreport" -> TestReport::class
                "testscript" -> TestScript::class
                "valueset" -> ValueSet::class
                "visionprescription" -> VisionPrescription::class
                else -> null
            }
        }
    }
}
