name: D4L CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  latest-version:

    runs-on: [self-hosted, macos]

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
      - name: Publish Snapshot to Maven Repo
        run: ./gradlew publishSnapshot
