name: D4L CI - Pull-Request Validation

on:
  pull_request:
    branches:
      - main
      - release/*
      - feature/*

jobs:
  pull-request-validation:

    runs-on: [self-hosted, macos]

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature
