name: D4L CI KMP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-verify:

    runs-on: [self-hosted, macos]

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
      - name: Run checks
        run: ./gradlew check
